### ISSUE TITLE
ArrayIndexOutOfBoundsException in DefaultMp4Builder.createStco

### ISSUE THREAD

**Issue by planedrover** [sannies/mp4parser#100]
I'm getting an ArrayIndexOutOfBoundsException with length=8; index=8 when trying to mux aac audio and raw h264 video into an mp4.

I'm using isoparser:1.0.6 from maven

The h264 video is generated using libopenh264

**Here's the exception:**
`Caused by: java.lang.ArrayIndexOutOfBoundsException: length=8; index=8
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createStco(DefaultMp4Builder.java:497)
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createStbl(DefaultMp4Builder.java:360)
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createTrackBox(DefaultMp4Builder.java:321)
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createMovieBox(DefaultMp4Builder.java:225)
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.build(DefaultMp4Builder.java:115)
            at com.smithmicro.mp4Parser.Mp4ParserAudioMuxer.muxH264VideoAACAudio(Mp4ParserAudioMuxer.java:49)
            at org.jcodec.jcodec_samples.MainActivity.DoOpenh264EncodeTest(MainActivity.java:177)
            at org.jcodec.jcodec_samples.MainActivity.onCreate(MainActivity.java:124)`

**Here's my code:**
```java
public static boolean muxH264VideoAACAudio(int fps, String h264VideoFile, String aacAudioFile, String outputFile){

        H264TrackImpl h264Track;
        AACTrackImpl aacTrack;

        try {
            h264Track = new H264TrackImpl(new FileDataSourceImpl(h264VideoFile), "eng", fps, 1);
            aacTrack = new AACTrackImpl(new FileDataSourceImpl(aacAudioFile), "eng");
        }
        catch(FileNotFoundException e){
            e.printStackTrace();
            return false;
        }
        catch (IOException e) {
            e.printStackTrace();
            return false;
        }

        Movie movie = new Movie();
        movie.addTrack(h264Track);
        movie.addTrack(aacTrack);

        Container mp4file = new DefaultMp4Builder().build(movie);

        try {
            FileChannel fc = new FileOutputStream(new File(outputFile)).getChannel();
            mp4file.writeContainer(fc);
            fc.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
            return false;
        }catch (IOException e) {
            e.printStackTrace();
            return false;
        }

        return true;
    }
```

**Comment by sannies** [comment]
Hi,
could you please send me the input files (h264VideoFile & aacAudioFile) so
I can debug this? (send me directly OR upload to a file share hoster as
github issues cannot have attachments)
Grüße,
Sebastian

2015-08-13 0:48 GMT+02:00 planedrover <notifications@github.com>:

**Comment by planedrover** [comment]
Hi,
Here¹s a zip with the audio.aac and video.264 files.

Let me know if you need any more info.

Thanks

Brian

From:  Sebastian Annies <notifications@github.com>
Reply-To:  sannies/mp4parser
<reply+00061811731fe254a0d606ba8c9d101e65392cfb8441a66d92cf0000000111e9f8349
2a169ce05ffd2d3@reply.github.com>
Date:  Monday, August 17, 2015 at 12:29 PM
To:  sannies/mp4parser <mp4parser@noreply.github.com>
Cc:  Brian Stuart <brian@kumatage.com>
Subject:  Re: [mp4parser] ArrayIndexOutOfBoundsException in
DefaultMp4Builder.createStco (#100)

Hi,
could you please send me the input files (h264VideoFile & aacAudioFile) so
I can debug this? (send me directly OR upload to a file share hoster as
github issues cannot have attachments)
Grüße,
Sebastian

2015-08-13 0:48 GMT+02:00 planedrover <notifications@github.com>:

> I'm getting an ArrayIndexOutOfBoundsException with length=8; index=8 when
> trying to mux aac audio and raw h264 video into an mp4.
>
> *Here's the exception:*
> Caused by: java.lang.ArrayIndexOutOfBoundsException: length=8; index=8
> at
> 
com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createStco(DefaultM
p4Builder.java:497)
> at
> 
com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createStbl(DefaultM
p4Builder.java:360)
> at
> 
com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createTrackBox(Defa
ultMp4Builder.java:321)
> at
> 
com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createMovieBox(Defa
ultMp4Builder.java:225)
> at
> 
com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.build(DefaultMp4Bui
lder.java:115)
> at
> 
com.smithmicro.mp4Parser.Mp4ParserAudioMuxer.muxH264VideoAACAudio(Mp4ParserAudio
Muxer.java:49)
> at
> 
org.jcodec.jcodec_samples.MainActivity.DoOpenh264EncodeTest(MainActivity.java:17
7)
> at org.jcodec.jcodec_samples.MainActivity.onCreate(MainActivity.java:124)
>
> *Here's my code:*
>
> public static boolean muxH264VideoAACAudio(int fps, String h264VideoFile,
String aacAudioFile, String outputFile){
>
>         H264TrackImpl h264Track;
>         AACTrackImpl aacTrack;
>
>         try {
>             h264Track = new H264TrackImpl(new
FileDataSourceImpl(h264VideoFile), "eng", fps, 1);
>             aacTrack = new AACTrackImpl(new FileDataSourceImpl(aacAudioFile),
"eng");
>         }
>         catch(FileNotFoundException e){
>             e.printStackTrace();
>             return false;
>         }
>         catch (IOException e) {
>             e.printStackTrace();
>             return false;
>         }
>
>         Movie movie = new Movie();
>         movie.addTrack(h264Track);
>         movie.addTrack(aacTrack);
>
>         Container mp4file = new DefaultMp4Builder().build(movie);
>
>         try {
>             FileChannel fc = new FileOutputStream(new
File(outputFile)).getChannel();
>             mp4file.writeContainer(fc);
>             fc.close();
>         } catch (FileNotFoundException e) {
>             e.printStackTrace();
>             return false;
>         }catch (IOException e) {
>             e.printStackTrace();
>             return false;
>         }
>
>         return true;
>     }
>
> 
> Reply to this email directly or view it on GitHub
> <https://github.com/sannies/mp4parser/issues/100>.
>


Reply to this email directly or view it on GitHub
<https://github.com/sannies/mp4parser/issues/100#issuecomment-131937115> .

**Comment by sannies** [comment]
Please send it to my private email or upload it somewhere. Github issues delete attachments when you update issues via email!

**Comment by sannies** [comment]
Hi,

I'm using this code in the master branch: 

        String baseDir = "C:\\Users\\sannies\\Downloads\\aac_h264\\";
        Movie av = new Movie();

        Track video = new H264TrackImpl(new FileDataSourceImpl(baseDir + "video.264"), "eng", 6, 1);
        Track audio = new AACTrackImpl(new FileDataSourceImpl(baseDir + "audio.aac"));
        av.addTrack(video);
        av.addTrack(audio);

        Mp4Builder builder = new DefaultMp4Builder();
        Container c = builder.build(av);
        c.writeContainer(new FileOutputStream("av.mp4").getChannel());

and I get a video. The h264 stream doesn't contain any timing information, you therefore need to set it directory. 

Would you please try version 1.1.2 from https://oss.sonatype.org/content/repositories/comgooglecodemp4parser-1071/

Best Regards,
Sebastian

**Comment by sannies** [comment]
if you rely on Android or any Java version <8 please use 1.1.3 from 1.1.3 and 
https://oss.sonatype.org/content/repositories/comgooglecodemp4parser-1072  as I acciedntally used Java 8 API in 1.1.2

**Comment by planedrover** [comment]
Both 1.1.2 and 1.1.3 give this exception, I compiling in Android Studio with java version 1.7.0_04:
```
java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:299)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
            at java.util.concurrent.FutureTask.run(FutureTask.java:239)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)
     Caused by: java.lang.NoSuchMethodError: java.util.List.sort
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createStco(DefaultMp4Builder.java:477)
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createStbl(DefaultMp4Builder.java:362)
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createTrackBox(DefaultMp4Builder.java:323)
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createMovieBox(DefaultMp4Builder.java:227)
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.build(DefaultMp4Builder.java:117)
```

**Comment by sannies** [comment]
Hi, that's weird. look at my change:
https://github.com/sannies/mp4parser/commit/56aa5e360f3dc6c254b066aa572bb605c3084bfe

do you still have 1.2.2 somewhere in your classpath?
In case I really botched the release could please try to build a snapshot
on your system. It should not take you long.

planedrover <notifications@github.com> schrieb am Di., 18. Aug. 2015 um
21:21 Uhr:

**Comment by planedrover** [comment]
I haven't been able to build mp4parser, I ran into issues with aspectj on Android Studio.

This is the file that Android studio opens when I get that exception:

C:\Users\username\.gradle\caches\modules-2\files-2.1\com.googlecode.mp4parser\isoparser\1.1.3\f9b933657eaddaa1d7448f903e5290009fd97ef1\isoparser-1.1.3-sources.jar!\com\googlecode\mp4parser\authoring\builder\DefaultMp4Builder.java

Here's the code in DefaultMp4Builder.java from isoparser-1.1.3-sources.jar
```
private InterleaveChunkMdat(Movie movie, Map<Track, int[]> chunks, long contentSize) {
            this.contentSize = contentSize;
            this.tracks = movie.getTracks();
            List<Track> tracks = new ArrayList<Track>(chunks.keySet());
  ----->    tracks.sort(new Comparator<Track>() {
                public int compare(Track o1, Track o2) {
                    return l2i(o1.getTrackMetaData().getTrackId() - o2.getTrackMetaData().getTrackId());
                }
            });
...........
}
```

**Comment by sannies** [comment]
This is what I fixed here:
https://github.com/sannies/mp4parser/commit/386b8b3f944ec2c96d6751e4499aa3ce39f0c9c2

you should be able to build it with maven:

download maven;
goto isoparser directory;
type "mvn install"

That should do it.



planedrover <notifications@github.com> schrieb am Di., 18. Aug. 2015 um
22:23 Uhr:

**Comment by planedrover** [comment]
Both tags 1.1.2 and 1.1.3 fail to build with jdk 1.7 but they do build with jdk 1.8

**Comment by sannies** [comment]
This is why you should please build master. We know that these Tags don't
work with anything below java 8

planedrover <notifications@github.com> schrieb am Di., 18. Aug. 2015 23:29:

**Comment by planedrover** [comment]
master doesn't build with jdk 1.7 either. It does build with jdk 1.8

**Comment by sannies** [comment]
I'll close the issue as I received notification that latest build works
