### ISSUE TITLE
cut video with the specail size

### ISSUE THREAD

**Issue by leon-ch** [sannies/mp4parser#104]
hi. there's a question, I want to use mp4parser to cut a video with specail size width:height, for example, 200:200, but the rawvideo is 640:480, can I do it with this?

**Comment by sannies** [comment]
If your plan is to decrease the filesize then it cannot be done as the
isoparser cannot re-encode the actual video frames.
You could try:
* Go into the SPS and change the cropping flags
* Change the matrices in tkhd/mvhd to resize before display
* Change the track width/height in the tkhd box

It all depends on what you really want to do.


2015-09-11 7:37 GMT+02:00 尘世流浪狗 <notifications@github.com>:

**Comment by deepakrokz** [comment]
Can you please explain it clearly, SPS and  tkhd/mvhd. Also one more help required to apply watermark very efficiently.
These will be very helpful. 
Thanks

**Comment by deepakrokz** [comment]
Please provide some sample as well for the above
