### ISSUE TITLE
No support for input MP4 files with SPS extension.

### ISSUE THREAD

**Issue by rdamiano** [sannies/mp4parser#105]
Hi again. I'm the person who created the topic about this issue on the Google Groups page (https://groups.google.com/forum/#!topic/mp4parser-discussion/uBoAkuf38uM).

I just wanted to make this an issue on Github so I can better track/be alerted when support is added for input files that use SPS extension as I'm currently working on an update to an app of mine that really needs this fix (I don't mean to rush you, however).

---

The issue occurs when opening an MP4 files that uses the SPS extension (jcodec produces these types of files):
```
H264TrackImpl h264Track = new H264TrackImpl(new FileDataSourceImpl("input.mp4"));
```
And crashes with:
```
09-01 18:46:40.611: E/AndroidRuntime(14115): FATAL EXCEPTION: GLThread 1260
09-01 18:46:40.611: E/AndroidRuntime(14115): Process: package.app, PID: 14115
09-01 18:46:40.611: E/AndroidRuntime(14115): java.lang.RuntimeException: Sequence parameter set extension is not yet handled. Needs TLC.
09-01 18:46:40.611: E/AndroidRuntime(14115): at com.googlecode.mp4parser.authoring.tracks.H264TrackImpl.readSamples(H264TrackImpl.java:362)
09-01 18:46:40.611: E/AndroidRuntime(14115): at com.googlecode.mp4parser.authoring.tracks.H264TrackImpl.parse(H264TrackImpl.java:108)
09-01 18:46:40.611: E/AndroidRuntime(14115): at com.googlecode.mp4parser.authoring.tracks.H264TrackImpl.<init>(H264TrackImpl.java:90)
09-01 18:46:40.611: E/AndroidRuntime(14115): at com.googlecode.mp4parser.authoring.tracks.H264TrackImpl.<init>(H264TrackImpl.java:96)
09-01 18:46:40.611: E/AndroidRuntime(14115): at com.googlecode.mp4parser.authoring.tracks.H264TrackImpl.<init>(H264TrackImpl.java:100)
09-01 18:46:40.611: E/AndroidRuntime(14115): at ...
```
Thanks!

**Comment by sannies** [comment]
Could you please make a file available. That shortens the time required on my side drastically! Thank you!

**Comment by rdamiano** [comment]
@sannies Sure, I actually attached one to a reply on the Google Group, here's the link to that attachment https://groups.google.com/d/msg/mp4parser-discussion/uBoAkuf38uM/AY-tuuvGBgAJ

**Comment by rdamiano** [comment]
@sannies Hey, I really don't want this to come across as demanding or me rushing you, I understand you're busy and that you do this stuff in your free time. I'm just wondering if there's any sort of ETA on this fix? I ask because I have an update for an app I'd like to push out that would utilize this MP4Parser functionality. Just wondering so I can plan my course of action.

**Comment by sannies** [comment]
I'll try to fix it today. There is only a limited time I can dedicate to
the project.

2015-10-12 22:32 GMT+02:00 Ralph <notifications@github.com>:

**Comment by sannies** [comment]
I'm so sorry that I didn't read your request entirely, thoroughly and fully
when you asked for the first time. I simply saw an error message and jumped
to a conclusion. My conclusion was absolutely wrong!
The line:

H264TrackImpl h264Track = new H264TrackImpl(new
FileDataSourceImpl("input.mp4"));

is not correct. The H264TrackImpl is a way to import raw (= Annex B) h264
streams where the NALs (network abstraction layer unit - smallest
selfcontained unit in h264) are transmitted with stop words in between: 00
00 00 01 [NAL] 00 00 00 01 [NAL] 00 00 00 01 [NAL] 00 00 00 01 [NAL] and so
on.
An MP4 file is a container and may contain more than just one stream (e.g.
it can contain audio and video) with supporting datastructures (comparable
to a table of contents in a book)

If you try to open an MP4 file with the H264TrackImpl it tries to interpret
the MP4 as Annex B H264 stream and obviously that doesn't work.

To open an MP4 file you should use the MovieCreator (stupid name - I know):

Movie v = new Movie();
Movie m = MovieCreator.build("Tears_Of_Steel_128000_eng.mp4");

for (Track track : m.getTracks()) {
    if ("soun".equals(track.getHandler())) {
        System.err.println("Adding audio track to new movie");
    } else if ("vide".equals(track.getHandler())) {
        System.err.println("Adding video track to new movie");
    } else {
        System.err.println("Adding " + track.getHandler() + " track to
new movie");
    }
    v.addTrack(track);
}





2015-10-13 8:57 GMT+02:00 Sebastian Annies <sebastian.annies@gmail.com>:

**Comment by rdamiano** [comment]
@sannies No problem at all, and thank you so much for taking the time to look into my issue. That code worked perfectly, everything is working great now. Thanks again!
