### ISSUE TITLE
How can I add or change boxes of a newly created Movie before storing?

### ISSUE THREAD

**Issue by rniebecker** [sannies/mp4parser#106]
Hi,

DefaultMp4Builder().build(movie) gives me a Container back which I can use to parse boxes but I can't change existing or add new boxes.

In older releases it looks like this could be done by casting the return value of DefaultMP4Builder to IsoFile but that is not working.

Right now I have to first store a temp mp4, use IsoFile to add/change the boxes and then I can store the final mp4.

Is there a better way of adding/changing boxes directly after or when creating a new Movie instead of using a temp file?

I'm using isoviewer-1.0-RC-28 on Android.

Cheers,
Ralf

**Comment by sannies** [comment]
Hi Ralf,
please don't use the isoviewer as dependency - it's a GUI tool to visualize ISOBMFF files. Use an isoparser-1.X.X.jar from the maven central repo.
There are two different ways to change the boxes: 

1. Subclass DefaultMp4Writer or FragmentedMp4Writer to insert the boxes while the structure is created
2. Navigate from the result of #build() - the Container you are talking about to the appropriate place and do the change there. The Container has a very similar API to start navigation from it: Container#getBoxes() gets all children Container#getBoxes(Class) gets all children of a specific class.  
You can as well use  Path#getPath(Container, String) to navigate with path expressions: 

   Container c = new DefaultMp4Writer().build();
   SampleDescriptionBox stsd = Path.getPath(c, "/moov[0]/trak[0]/mdia[0]/minf[0]/stbl[0]/stsd[0]");

Does that answer your question?

**Comment by rniebecker** [comment]
Hi Sebastian,

thanks for taking your time to answer! :)

I upgraded to using isoparser 1.1.7 now, I had to do some changes in my code because some of the methods I used for calculating sample times were outdated but the newer ones are really much more helpful and everything seems to work as before. I can now parse some videos I had problems with before, which were causing array out of bounds exceptions when writing the movie.

I needed to change the contents of the file type box and I'm doing that now by overriding createFileTypeBox() of DefaultMP4Writer and setting my values for MajorBrand etc.

Additionally I'm adding 2 user boxes by casting the Container I retrieve when doing DefaultMp4Builder() to BasicContainer which allows me to simply add boxes before calling writeContainer().

One other question: Is there a way of getting progress updates when calling writeContainer() so I can show a progress bar while the movie is being written? Right now I'm guessing the time writeContainer() needs with a simple calculation and I'm using a TimerTask to update the progress on screen. This works OK but a real progress visualization would be nicer. My problem with this is that there are hundreds of different Android devices out there which perform differently when doing this operation.

Keep up the great work, it's really appreciated! Love your library ...

Cheers,
Ralf

**Comment by sannies** [comment]
I thought about progress listeners for some time but came to the conclusion that it would be very hard to implement in a meaningful way.  There are three progresses to track: 

1. Reading the input MP4/H264/AAC file/Creating the Movie object. While reading through an H264 and AAC is straightforward and it's easy to track progress (if you read up to byte 10000 in a 100KB file you are obviously at 10%) it might get harder when accessing MP4 - Who knows if I'm done with the time consuming stuff? Will the structure change later in the file?

2. Creation of the 'model' e.g. the container: This is typically quite fast but certain operations - perhaps even in derived classes might be time-consuming depending on the input. How would I know how much of the heavy lifting is already done? Is it worth the effort if the creation of the model only takes seconds?

3. The actual file creation (Writing to the WritableByteChannel): Is that something that should be done in the library or is it something that can be done from the outside with not much effort and reasonable precision? My approach there would be to estimate the file size by adding up all sample sizes, adding 10% for muxing overhead and then comparing it continuously with the file's size on the SD card/harddisk.

**Comment by rniebecker** [comment]
Thanks again for your thorough answer! I think for now I'll stick to my solution where I calculate the time based on seconds of the clip that is being processed which is OK so far because all clips I'm processing have the same bitrate and I'm adding some time for slower devices. No one is complaining if the processing is finished earlier. :)

Later on I might switch to using the approach you described in 3.

Cheers,
Ralf
