### ISSUE TITLE
Adding tracks on specific time

### ISSUE THREAD

**Issue by leo150** [sannies/mp4parser#107]
Hi! Can I add tracks to video on specific time using mp4parser? 

![screen shot 2015-09-25 at 02 01 44](https://cloud.githubusercontent.com/assets/3484524/10089188/8320aa52-6329-11e5-9a30-77ca676ed97c.png)

**Comment by sannies** [comment]
Hi Leo,

unfortunately an operation like that cannot be performed on container
level. It require merging of the track1,2,3,4,5 into a single track. This
operation requires reencoding - especially as it seems to require mixing of
the track 1 and 2 - they are audible at the same time.
In theory MP4 can do that but in practice the players won't support
multiple audio tracks to be active at the same time.
If you are on Android I guess you should use the MediaCodec API. On Server
OS I'd use ffmpeg or similar tools.
You can after re-encoding of course mux the audio and the video with the
mp4parser.

Hope that helps,
Sebastian


2015-09-25 1:04 GMT+02:00 leo150 <notifications@github.com>:

**Comment by leo150** [comment]
Thank you for support! I'll try to play around reencoding
