### ISSUE TITLE
Video streaming

### ISSUE THREAD

**Issue by abdallah95** [sannies/mp4parser#108]
Hello :) 
I'm trying to implement a live video streaming app on android, the server is sending udp packets containing the video data, assuming that all devices are connected before the beginning of the transmission, they all receive the file and plays it, but i'm considering the case where some device connects in the middle of the transmission or even the case where there is packet loss, i looked it up and found that i should use fragmented mp4 files, and it means that each mp4 file is fragmented into smaller chunks of mp4 files, each fragment has its own header(or called moof box)(right? :p), and that could be helpful, in case of packet loss or if someone connected in the middle of transmission i can just skip till next fragment, what could be the size of a single fragment and how could i locate the position of each fragment in the byte stream? and does videoview in android supports fragmented mp4 files?

**Comment by sannies** [comment]
Hi Abdallah,
fragmented MP4 are typically supported by Android (but I never tested the
extend of the support). The 1.1.x branch is not very suitable for
streaming. The 2.x branch is prepared for that and I already made an
example that is at relatively close to what you are doing. Have a look at
my RTP2DASH <https://github.com/sannies/rtp2dash> project. It receives RTP
packets (That's a UDP based protocol as well!) and emits DASH streams - but
you don't need the DASH part.  Have a look at the Server class:
Everything from line 124 is HTTP server related. You don't need that. The
lines

writers.add(new DashFragmentedMp4Writer(aac_ita, baseDir));
writers.add(new DashFragmentedMp4Writer(aac_eng, baseDir));
writers.add(new DashFragmentedMp4Writer(h264_0, baseDir));
writers.add(new DashFragmentedMp4Writer(h264_1, baseDir));
writers.add(new DashFragmentedMp4Writer(h264_2, baseDir));
writers.add(new DashFragmentedMp4Writer(h264_3, baseDir));

need to be changed as the DashFragmentedMp4Writer is only writing DASH
segments but no full files. You might want to change it to e.g.

writers.add(new
MultiTrackFragmentedMp4Writer(Collections.singletonList(h264_0), new
FileOutputStream("output-file.mp4")));

The last is step would be to adopt the data receiving class
RtpH264StreamingTrack to receive your data format. That shouldn't be too
hard, right?

Best Regards,
Sebastian

-------------------------
If you fail: No worries - I'm available for freelance work.

2015-09-26 13:27 GMT+02:00 Abdallah Moussawi <notifications@github.com>:
