### ISSUE TITLE
Ordering of Video and Audio Samples in MP4

### ISSUE THREAD

**Issue by rniebecker** [sannies/mp4parser#110]
Hi Sebastian,

I'm playing around with ExoPlayer and I ran into some issues when I cut a video or merge several clips using isoparser 1.1.7. I've been using your examples to do those jobs and with the normal Android MediaPlayer everything is fine but when using ExoPlayer it stops after rendering the first frame.
This is because it seems that if ExoPlayer can't find audio samples in the region it's buffering it's not playing back the video.

I worked around this by using 2 different SampleSources of ExoPlayer, one for video and one for audio, which is not a good solution because I have 2 Extractors working on the same file now.

I did some testing with ffprobe (ffprobe -i cut2.mp4 -show_frames | grep -E 'media_type|pts_time') and I see that the video and audio samples are not written in chronological order after creating a new Movie with isoparser.

The original video looks like the video and audio samples are pretty much sorted by pts ascending while the video cut using isoparser has the samples stored in what looks like video and audio blocks.

Is there a way of changing the ordering of the samples based on their pts when writing a movie?

Cheers,
Ralf

**Comment by sannies** [comment]
Hi Ralf,

are you using traditional MP4 (DefaultMp4Writer) or fragmented MP4
(FragmentedMp4Writer)?
Let me elaborate a bit:
In traditional MP4 there are the so called chunks - bundles of audio or
video samples. In fragmented MP4 there are  - surprise - fragments. The
order of the fragments/chunks (Frag1, Frag2, ..., Fragn, ... FragN ) should
make sure that the function f(n) = PTS(1st sample in the fragment/segment)
is monotonic increasing. If that is not the cause I made a mistake that
needs to be corrected.
Could you perhaps send me an example? It's always easier to work with
examples!

Thx und beste Grüße,
Sebastian


2015-09-28 12:17 GMT+02:00 rniebecker <notifications@github.com>:

**Comment by rniebecker** [comment]
Hi Sebastian,

I'm using the DefaultMP4Writer. Using FragmentedMp4Writer creates videos that can't be read by the FragmentedMp4Extractor of ExoPlayer - don't know if that is an issue with ExoPlayer or with isoparser.

Anyways it's hard to sent you an example because my files are very large (20mbit encoded) which is part of the problem because the ExoPlayer is probably running out of buffer space before it read enough audio samples for playback so it simply stops.

I read in one of your answers that you are doing interleaving of audio and video samples in 2 second intervals. Is there a way of changing that to doing 0.5 seconds? Is that only happening when using FragmentedMp4Writer or is the DefaultMp4Writer doing that as well?

Cheers & schöne Grüße nach Hamburg,
Ralf

PS: One other unrelated question, do you have experience working with OpenCV/JavaCV?

**Comment by sannies** [comment]
You can set the Fragmenter at the DefaultMp4Builder.  Unfortunately my
supplied implementation is rather stupid and only accept "int" as time but
it's super easy to implement - use this slightly modified version (simply
copy it into your code):

public class TimeBasedFragmenter implements Fragmenter {
    private double fragmentLength = 2;

    public TimeBasedFragmenter(double fragmentLength) {
        this.fragmentLength = fragmentLength;
    }

    /**
     * {@inheritDoc}
     */
    public long[] sampleNumbers(Track track) {
        long[] segmentStartSamples = new long[]{1};
        long[] sampleDurations = track.getSampleDurations();
        long[] syncSamples = track.getSyncSamples();
        long timescale = track.getTrackMetaData().getTimescale();
        double time = 0;
        for (int i = 0; i < sampleDurations.length; i++) {
            time += (double) sampleDurations[i] / timescale;
            if (time >= fragmentLength &&
                    (syncSamples == null ||
Arrays.binarySearch(syncSamples, i + 1) >= 0)) {
                if (i > 0) {
                    segmentStartSamples =
Mp4Arrays.copyOfAndAppend(segmentStartSamples, i + 1);
                }
                time = 0;
            }
        }
        return segmentStartSamples;
    }
}

and set the Fragmenter like this

DefaultMp4Builder b = new DefaultMp4Builder();
b.setFragmenter(new TimeBasedFragmenter(0.5));

DefaultMp4Builder and FragmentedMp4Builder use different Fragmenters (for
no particular reason - I just didn't change it). Both can use the
TimeBasedFragmenter from this email.

Hope that helps.
Sebastian


2015-09-28 14:14 GMT+02:00 rniebecker <notifications@github.com>:

**Comment by rniebecker** [comment]
Awesome!

Working like a charm!

Vielen Dank & Liebe Grüße,
Ralf
