### ISSUE TITLE
Wrong duration in mp4 container

### ISSUE THREAD

**Issue by HPIWicket** [sannies/mp4parser#115]
We generate a mp4 file by creating a movie and adding an aac track and an h264 track.

ffprobe displays the following results for the file:

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'video_file_wrong.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 0
    compatible_brands: isomiso2avc1
    creation_time   : 2015-10-06 13:21:21
  Duration: 00:00:01.00, start: 0.000000, bitrate: 1385 kb/s
    Stream #0:0(eng): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p, 480x480, 716 kb/s, 29 fps, 29 tbr, 29 tbn, 58 tbc (default)
    Metadata:
      creation_time   : 2015-10-06 13:21:21
      encoder         : AVC Coding
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 22050 Hz, mono, fltp, 47 kb/s (default)
    Metadata:
      creation_time   : 2015-10-06 13:21:08
```

When we set the minor_version manually after the we build the mp4 file with the DefaultMp4Builder to 512 we get the correct information (major_brand is correct now too).

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Tolle_Karte_06-10-2015_20-05.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 512
    compatible_brands: mp42isom
    creation_time   : 2015-10-06 14:35:20
  Duration: 00:00:01.77, start: 0.000000, bitrate: 778 kb/s
    Stream #0:0(eng): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p, 480x480, 721 kb/s, 30 fps, 30 tbr, 30 tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2015-10-06 14:35:20
      encoder         : AVC Coding
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 22050 Hz, mono, fltp, 47 kb/s (default)
    Metadata:
      creation_time   : 2015-10-06 14:35:07
```

It would be good to know if this is an error on our side or if the minor_version is wrong in the library.

Cheers,
Richard

**Comment by sannies** [comment]
I guess ffprobe is right.  The file uses features that require mp42
compatibility from the player at least.  I  will have a look if it
potentially even uses features from a later spec version and adopt
accordingly.  Version 1 of the ctts box for example might only be supported
later.  Luckily - or perhaps sadly - almost no player checks the ftyp box.
Therefore muxers stopped paying attention and this information be came even
more useless.

Best Regards,  Sebastian
Am 06.10.2015 16:48 schrieb "Richard Meissner" <notifications@github.com>:

**Comment by HPIWicket** [comment]
Thanks for the info. The workaround seems to work right now. QuickTime (and therefore all of the iOS devices) was the only one that really used this duration and didn't play the video until the end.

Regards
Richard
