### ISSUE TITLE
How can I add UUID UserBoxes directly after the FileTypeBox?

### ISSUE THREAD

**Issue by rniebecker** [sannies/mp4parser#116]
Hi Sebastian,

I'm creating a new video on Android using MediaMuxer and I'm using IsoParser to add additional UUID boxes after the video is created and to fragment the audio/video samples properly.

The newly added boxes end up after the mdat box in the resulting file. These boxes are needed to determine the way the video should be played back and should be stored directly after the FileTypeBox in the root box/container to make sure streaming is working properly.

I haven't found a way of doing this, I tried using a BasicContainer with Path.getPath(mContainer, "/") and then use addBox() but that fails with an Exception telling me I'm not allowed to access it.

Is there any other way of doing this using IsoParser?

Liebe Grüße nach Hamburg,
Ralf

**Comment by sannies** [comment]
Hi Ralf, 
I never tested that. What is the exact exception?
I would propose to do something like this:

    IsoFile isoFile = new IsoFile("your file.mp4");
    List<Box> boxes = isoFile.getBoxes();
    Box uuid = new UUID("dontknowwhat") {};
    boxes.add(2, uuid);
    WritableByteChannel wbc = new FileOutputStream("out file.mp4").getChannel();
    for (Box b : boxes) {
        boxes.getBox(wbc)
    }

this will add the uuid box at position 2.

In the very near future I'll publish isoparser 2.0 and with it an example on how to use it instead of mediamuxer on android. That will all nice use cases such as add GPS data in a subtitle track without reading/changing/writing again the whole file

**Comment by rniebecker** [comment]
Hi Sebastian,

I was traveling the last 2 weeks. I tested this and indeed the boxes end up where I want them to but I can't playback the video when I do this change. Are there any offsets I need to correct? The UUID boxes end up directly after the FileTypeBox which is the first box.

Liebe Grüße nach Hamburg,
Ralf

**Comment by sannies** [comment]
In deed, you have to correct offsets.
Have a look here:


2015-10-25 19:16 GMT+01:00 rniebecker <notifications@github.com>:

**Comment by rniebecker** [comment]
Hi Sebastian,

the UUID boxes are added before the mdat and the moov box so the offset should stay the same or are the offsets calculated absolute from file start?

Cheers,
Ralf

**Comment by sannies** [comment]
If you are using classic MP4  (ftyp, moov, mdat) then the offset is calculated from the beginning of the file.
