### ISSUE TITLE
Appending time lapse and normal mode videos

### ISSUE THREAD

**Issue by bhuvneshvarma** [sannies/mp4parser#118]
Using this library Can we append two videos with different capture rates?

**Comment by sannies** [comment]
The frame rate is not the decisive factor.  Encoding settings,  SPS and PPS
must be the same.

bhuvneshvarma <notifications@github.com> schrieb am So., 18. Okt. 2015 7:55
PM:

**Comment by bhuvneshvarma** [comment]
i see in document its written-
It is important to emphasize that you cannot append any two tracks with:

Different resolutions
Different frame-rates

Can i append time lapse and normal mode videos with this library?

**Comment by sannies** [comment]
What kind of timelapse do you have? Is the frame lower or is it a normal
video showing slow motion?
Make an example available and I'll be able to tell.

2015-10-19 6:41 GMT+02:00 bhuvneshvarma <notifications@github.com>:

**Comment by bhuvneshvarma** [comment]
yeah..video showing slow motion..Time lapse video u can its document here.. http://developer.android.com/intl/es/guide/topics/media/camera.html#time-lapse-video
I used ur library..it works fine for appending same mode videos..but i want to append different mode videos-time lapse and normal mode video..How should i proceed in tht?I tried below code for merging videos in Vid directory which works fine if all videos are in same mode but fails to append if videos are of different mode.

public class MergedVideo extends AsyncTask<Void, Integer, String> {
    @Override
    protected void onPreExecute() {
    }
    ;
    @Override
    protected String doInBackground(Void... voids) {
        try {
            File mediaStorageDir = new File(Environment.getExternalStoragePublicDirectory(
                    Environment.DIRECTORY_PICTURES), "Vid");
            File f = new File(mediaStorageDir.getPath());
            File file[] = f.listFiles();
            String paths[] = new String[file.length];
            Movie[] inMovies = new Movie[file.length];
            for (int i = 0; i < file.length; i++) {
                paths[i] = file[i].getPath();
                inMovies[i] = MovieCreator.build(paths[i]);
            }
            List<Track> videoTracks = new LinkedList<Track>();
            List<Track> audioTracks = new LinkedList<Track>();
            for (Movie m : inMovies) {
                for (Track t : m.getTracks()) {
                    if (t.getHandler().equals("soun")) {
                        audioTracks.add(t);
                    }
                    if (t.getHandler().equals("vide")) {
                        videoTracks.add(t);
                    }
                }
            }
            Movie result = new Movie();
            if (audioTracks.size() > 0) {
                result.addTrack(new AppendTrack(audioTracks
                        .toArray(new Track[audioTracks.size()])));
            }
            if (videoTracks.size() > 0) {
                result.addTrack(new AppendTrack(videoTracks
                        .toArray(new Track[videoTracks.size()])));
            }
            BasicContainer out = (BasicContainer) new DefaultMp4Builder()
                    .build(result);
            @SuppressWarnings("resource")
            FileChannel fc = new RandomAccessFile(String.format(Environment
                    .getExternalStorageDirectory() + "/mergedvideo.mp4"),
                    "rw").getChannel();
            out.writeContainer(fc);
            fc.close();
        } catch (FileNotFoundException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
            Log.e("Bhu", e.toString());
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
            Log.e("Bhu", e.toString());
        }
        String mFileName = Environment.getExternalStorageDirectory()
                .getAbsolutePath();
        mFileName += "/mergedvideo.mp4";
        return mFileName;
    }

**Comment by sannies** [comment]
The mp4parser cannot encode videos. All mp4parser operations are on
'container-level' not on 'codec-level'. So: If the codec setting are
different then it won't work but I can't tell from looking at the
documentation.
As I said: Make an example available and I'll check.

2015-10-19 17:36 GMT+02:00 bhuvneshvarma <notifications@github.com>:

**Comment by bhuvneshvarma** [comment]
I am recording video from camera and storing in device storage...All video I am storing in particular storage.Below is the code I am using for downloading time lapse and normal mode videos and below that is the code I am using for appending them..If you allow I can share with you two files of video out of which one is time lapse video and other is normal mode video to check if they can be appended with this library

For capturing time lapse video-


                        if (prepareFastVideoRecorder()) {

                            mMediaRecorder.start();

                        } else {

                            releaseMediaRecorder();
                        }

  

                private boolean prepareFastVideoRecorder() {
        
                mMediaRecorder = new MediaRecorder();
        
        
                mCamera.unlock();
                mMediaRecorder.setCamera(mCamera);
                mMediaRecorder.setVideoSource(MediaRecorder.VideoSource.DEFAULT);
        
        
                mMediaRecorder.setProfile(CamcorderProfile.get(0, CamcorderProfile.QUALITY_TIME_LAPSE_480P));
              
                mMediaRecorder.setCaptureRate(5); 
        
                // Step 4: Set output file to the socket
                mVideoFile = new File(getOutputMediaFile().toString());
                mMediaRecorder.setOutputFile(mVideoFile.getAbsolutePath());
                if (cameratype == 1)
                    mMediaRecorder.setOrientationHint(90);
                else if (cameratype == 2)
                    mMediaRecorder.setOrientationHint(270);
                mMediaRecorder.setMaxDuration(60000);
                mMediaRecorder.setOnInfoListener(this);
                // Step 5: Set the preview output
                mMediaRecorder.setPreviewDisplay(mPreview.getHolder().getSurface());
        
                try {
                    mMediaRecorder.prepare();
        
                } catch (IllegalStateException e) {
        
                    releaseMediaRecorder();
                    return false;
                } catch (IOException e) {
        
                    releaseMediaRecorder();
                    return false;
                }
                return true;
            }
For capturing normal video-

                        if (prepareFastVideoRecorder()) {

                            mMediaRecorder.start();

                        } else {

                            releaseMediaRecorder();
                        }

    private boolean prepareVideoRecorder() {
    
    
            mMediaRecorder = new MediaRecorder();
    
    
            mCamera.unlock();
            mMediaRecorder.setCamera(mCamera);
    
    
            mMediaRecorder.setAudioSource(MediaRecorder.AudioSource.CAMCORDER);
            mMediaRecorder.setVideoSource(MediaRecorder.VideoSource.CAMERA);
 
    
    
            mMediaRecorder.setProfile(CamcorderProfile.get(CamcorderProfile.QUALITY_HIGH));
    
            mVideoFile = new File(getOutputMediaFile().toString());
            mMediaRecorder.setOutputFile(mVideoFile.getAbsolutePath());
    
            mMediaRecorder.setPreviewDisplay(mPreview.getHolder().getSurface());
            if (cameratype == 1)
                mMediaRecorder.setOrientationHint(90);
            else if (cameratype == 2)
                mMediaRecorder.setOrientationHint(270);
    
            mMediaRecorder.setMaxDuration(10000);
            mMediaRecorder.setOnInfoListener(this);
    
    
            try {
                mMediaRecorder.prepare();
            } catch (IllegalStateException e) {
                Log.d("CAMERA", "IllegalStateException preparing MediaRecorder: " + e.getMessage());
                releaseMediaRecorder();
                return false;
            } catch (IOException e) {
                Log.d("CAMERA", "IOException preparing MediaRecorder: " + e.getMessage());
                releaseMediaRecorder();
                return false;
            }
    
            return true;
        }
Merging Video

    public class MergedVideo extends AsyncTask<Void, Integer, String> {
    
    
    
    
            @Override
            protected void onPreExecute() {

            }
    
        
        @Override
        protected String doInBackground(Void... voids) {
            try{
                    File mediaStorageDir = new File(Environment.getExternalStoragePublicDirectory(
                            Environment.DIRECTORY_PICTURES), "Vid");
  
                    File f = new File(mediaStorageDir.getPath());
                    File file[] = f.listFiles();
                    Log.e("FilesBhuv", "Size: " + file.length);
                    String paths[] = new String[file.length];
                    Movie[] inMovies = new Movie[file.length];
                    for (int i = 0; i < file.length; i++) {
                        paths[i] = file[i].getPath();
                     
                    
                        inMovies[i] = MovieCreator.build(paths[i]);
    
                       
                    }
    
 
                    List<Track> videoTracks = new LinkedList<Track>();
                    List<Track> audioTracks = new LinkedList<Track>();
                    for (Movie m : inMovies) {
                        for (Track t : m.getTracks()) {
                            if (t.getHandler().equals("soun")) {
                                audioTracks.add(t);
                            }
                            if (t.getHandler().equals("vide")) {
                                videoTracks.add(t);
                            }
                        }
                    }
    
                    Movie result = new Movie();
    
                    if (audioTracks.size() > 0) {
                        result.addTrack(new AppendTrack(audioTracks
                                .toArray(new Track[audioTracks.size()])));
                    }
                    if (videoTracks.size() > 0) {
                        result.addTrack(new AppendTrack(videoTracks
                                .toArray(new Track[videoTracks.size()])));
                    }
    
                    BasicContainer out = (BasicContainer) new DefaultMp4Builder()
                            .build(result);
    
                    @SuppressWarnings("resource")
                    FileChannel fc = new RandomAccessFile(String.format(Environment
                            .getExternalStorageDirectory() + "/mergedvideo.mp4"),
                            "rw").getChannel();
                    out.writeContainer(fc);
                    fc.close();
                } catch (FileNotFoundException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                    Log.e("Bhuvnesh",e.toString());
                } catch (IOException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                    Log.e("Bhuvnesh", e.toString());
                }
                String mFileName = Environment.getExternalStorageDirectory()
                        .getAbsolutePath();
                mFileName += "/mergedvideo.mp4";

                return mFileName;
            }

**Comment by sannies** [comment]
Yes please share the files.  Upload them somewhere. Github issues cannot
have attachments

bhuvneshvarma <notifications@github.com> schrieb am Mo., 19. Okt. 2015 8:21
PM:

**Comment by bhuvneshvarma** [comment]
I have sent you the files on email- Sebastian.Annies@googlemail.com ..Thanks a lott!!!

**Comment by bhuvneshvarma** [comment]
it worked..thanks a lott!!

**Comment by flieks** [comment]
Hi Please what was the solution ? I also want to put my video in slow motion (android)

**Comment by fxhereng** [comment]
Hi, 

I'm having the same problem here, I record mp4 videos (15 fps, h264 Baseline profile) and I'm trying to append it with a VOB video that I am converting manually to h264 Baseline profile, 15fps as well but they don't have the same bitrate.  I'm using ffmpeg to do so.

How do I record the timelapse video: 
```java
 @TargetApi(Build.VERSION_CODES.HONEYCOMB)
    private boolean prepareVideoRecorder() {

        // BEGIN_INCLUDE (configure_preview)
        mCamera = CameraHelper.getDefaultCameraInstance();

        // We need to make sure that our preview and recording video size are supported by the
        // camera. Query camera to find all the sizes and choose the optimal size given the
        // dimensions of our preview surface.
        Camera.Parameters parameters = mCamera.getParameters();
        List<Camera.Size> mSupportedPreviewSizes = parameters.getSupportedPreviewSizes();
        List<Camera.Size> mSupportedVideoSizes = parameters.getSupportedVideoSizes();
        List<int[]> supportedPreviewFpsRange = parameters.getSupportedPreviewFpsRange();
        Camera.Size optimalSize = CameraHelper.getOptimalVideoSize(mSupportedVideoSizes,
                mSupportedPreviewSizes, mPreview.getWidth(), mPreview.getHeight());

        // Use the same size for recording profile.
        CamcorderProfile profile = CamcorderProfile.get(CamcorderProfile.QUALITY_HIGH);
        profile.videoFrameWidth = optimalSize.width;
        profile.videoFrameHeight = /*optimalSize.height*/720;

        // likewise for the camera object itself.
        parameters.setPreviewSize(profile.videoFrameWidth, profile.videoFrameHeight);
        mCamera.setParameters(parameters);
 
        try {
            // Requires API level 11+, For backward compatibility use {@link setPreviewDisplay}
            // with {@link SurfaceView}
            mCamera.setPreviewTexture(mPreview.getSurfaceTexture());
        } catch (IOException e) {
            Log.e(TAG, "Surface texture is unavailable or unsuitable" + e.getMessage());
            return false;
        }
        // END_INCLUDE (configure_preview)


        // BEGIN_INCLUDE (configure_media_recorder)
        mMediaRecorder = new MediaRecorder();

        // Step 1: Unlock and set camera to MediaRecorder
        mCamera.unlock();
        mMediaRecorder.setCamera(mCamera);
        //mMediaRecorder.setOrientationHint(90); //Quit if landsacpe wanted

        // Step 2: Set sources
        mMediaRecorder.setAudioSource(MediaRecorder.AudioSource.CAMCORDER);
        mMediaRecorder.setVideoSource(MediaRecorder.VideoSource.CAMERA);

        // Step 3: Set a CamcorderProfile (requires API Level 8 or higher)
        mMediaRecorder.setProfile(profile);

        // Step 4: Set output file
        mOutputFile = CameraHelper.getOutputMediaFile(CameraHelper.MEDIA_TYPE_VIDEO);
        if (mOutputFile == null) {
            return false;
        }
        Log.i(TAG, "mOutputFile path: " + mOutputFile.getAbsolutePath());
        mMediaRecorder.setOutputFile(mOutputFile.getPath());

        mMediaRecorder.setVideoFrameRate(profile.videoFrameRate / 2);
        mMediaRecorder.setVideoEncodingBitRate(profile.videoBitRate / 2);
        mMediaRecorder.setCaptureRate(profile.videoFrameRate);

        // END_INCLUDE (configure_media_recorder)

        // Step 5: Prepare configured MediaRecorder
        try {
            mMediaRecorder.prepare();
        } catch (IllegalStateException e) {
            Log.d(TAG, "IllegalStateException preparing MediaRecorder: " + e.getMessage());
            releaseMediaRecorder();
            return false;
        } catch (IOException e) {
            Log.d(TAG, "IOException preparing MediaRecorder: " + e.getMessage());
            releaseMediaRecorder();
            return false;
        }
        return true;
    }
```

How Do I append the two videos:
```java
  public static void appendTwoVideos(File videoFile1, File videoFile2) throws IOException {
        readVideoMetaData(videoFile1);
        readVideoMetaData(videoFile2);

        Movie movie1 = MovieCreator.build(videoFile1.getAbsolutePath());
        Movie movie2 = MovieCreator.build(videoFile2.getAbsolutePath());

        List<Track> videoTracks = new LinkedList<>();
        List<Track> audioTracks = new LinkedList<>();

        for (Track track : movie1.getTracks()) {
            Log.i(TAG, "movie1: " + track.getHandler());
            if (track.getHandler().equals("soun")) {
                audioTracks.add(track);
            }
            if (track.getHandler().equals("vide")) {
                videoTracks.add(track);
            }
        }

        for (Track track : movie2.getTracks()) {
            Log.i(TAG, "movie2: " + track.getHandler());
            if (track.getHandler().equals("soun")) {
                audioTracks.add(track);
            }
            if (track.getHandler().equals("vide")) {
                videoTracks.add(track);
            }
        }

        Movie result = new Movie();

        if (!audioTracks.isEmpty()) {
            result.addTrack(new AppendTrack(audioTracks.toArray(new Track[audioTracks.size()])));
        }
        if (!videoTracks.isEmpty()) {
            result.addTrack(new AppendTrack(videoTracks.toArray(new Track[videoTracks.size()])));
        }

        try {
            Container out = new DefaultMp4Builder().build(result);

            FileChannel fc = new RandomAccessFile(String.format(Environment.getExternalStoragePublicDirectory(
                    Environment.DIRECTORY_PICTURES) + "/mergedvideo.mp4"),
                    "rw").getChannel();

            out.writeContainer(fc);
            fc.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

config video captured by the device:
![vid_15fps](https://cloud.githubusercontent.com/assets/5686128/21992924/b0559a6e-dc18-11e6-9ea6-d27d88dd6236.png)

config video of the one i'm trying to append:
![splash_test_config](https://cloud.githubusercontent.com/assets/5686128/21992931/b76751d0-dc18-11e6-8549-bbf09eeeb6a0.png)

Thanks for your help

**Comment by raghavtilak** [comment]
Hey @bkjbkjbnkj687698698 
5 year after I was reading your discussion with @sannies. At last you send him an email and he solved your problem. You left all of us in mystery.
**So, could you please share the solution with us because I am also stuck in appending videos of different framerates**
I have used ffmpeg but its too slow.

I know its 5 years but please acknowledge. It would be a great help.

**Comment by sannies** [comment]
While I don't have a solution beside the advise to reencode with ffmpeg or with the Android H264 encoder there are still many things one could try - depending on the capabilities of the playback device and your use-case. 
1.) Try to create an AVC1 track with multiple SPS/PPS. 
2.) Try to use AVC3 and signal the configuration change inband
3.) Convert everything into an MPEG-DASH stream with 2 periods.

I don't support this project any longer. I feel that it's valuable to many people but no one ever paid me to do it and I got to pay my rent.

**Comment by raghavtilak** [comment]
Thank you @sannies for showing your concern.
Although I haven't heard about any of these but still I will try to find something from the internet.

@sannies Actually we all are same. We too have our expenses and we try to find some open source or free codes from the internet. So it is difficult for us to buy you a coffee.
Don't worry hard work always pays off. Your help is unconditional and at some point in your life you will be successful and you would definetly buy a home for yourself.
