### ISSUE TITLE
How to trim video on external SD card Android 5.0?

### ISSUE THREAD

**Issue by sunshinetpu** [sannies/mp4parser#119]
I need to trim a video, which is located on external SD card. 
For videos in primary storage, I can use:
Movie movie = MovieCreator.build(mMediaPath); 

But we cannot use FilePath for videos on external SD card on Android 5.0. The only way to access those video is getting their Uri. 

How can I create movie from Uri of video?

**Comment by sannies** [comment]
Hi [whateveryournameis],

typically you can access the files with their full path such
as  /extSdCard/movies/movie.mp4. There should be a way to get that path
(but I'm no Android expert). I am aware that there might be some devices
that restrict the access to the SD card for apps. This might be a problem -
I can see that - but with the current API you need random access on the
datasource. Have a look at the DataSource interface at
https://github.com/sannies/mp4parser/blob/master/isoparser/src/main/java/com/googlecode/mp4parser/DataSource.java
- can you somehow implement that interface with a URI as datasource?

In a few weeks I'll have version 2 of the mp4parser ready which will
provide ways to read MP4 files from a normal InputStream.

Best Regards,
Sebastian

2015-10-20 5:55 GMT+02:00 sunshinetpu <notifications@github.com>:

**Comment by AndroidDeveloperLB** [comment]
@sannies Is loading from InputStream available?

Currently we have this:

    Movie movie = MovieCreator.build(new FileDataSourceViaHeapImpl(filePath));

But on Android, sometimes all we have is a `Uri` and a `ContentResolver` to create an `InputStream` from it. 

If the answer is that we have one for InputStream, could you please show how to use it, and maybe update the main page of the repository? Which version of the repository should I use?

**Comment by AndroidDeveloperLB** [comment]
Seeing that this is closed, does it mean that it's possible now to use InputStream or Uri ?

If so, I've written a question about it here:

https://github.com/sannies/mp4parser/issues/357
