### ISSUE TITLE
Replacing audio of video

### ISSUE THREAD

**Issue by bhuvneshvarma** [sannies/mp4parser#121]
Hello,
I want to replace an audio of a video with another audio(not append).In other words,I want to remove audio from the video and add other audio to the video.Is it possible through this library?

**Comment by sannies** [comment]
Create a Movie object. Identify the audio track in the list of tracks
(Movie#getTracks) via Track#getHandler == 'soun'. Remove the track from the
list. Add another audio track of your choice and feed everything into the
DefaultMp4Builder or FragmentedMp4Builder.

2015-10-21 13:53 GMT+02:00 bhuvneshvarma <notifications@github.com>:

**Comment by bhuvneshvarma** [comment]
Okay thanks.Below i have added some code..is this way i should proceed?

    try {
    String baseDir = Environment.getExternalStorageDirectory().getAbsolutePath();
    H264TrackImpl h264Track = new H264TrackImpl(new FileDataSourceImpl(baseDir + "/video.h264"));
    AACTrackImpl aacTrack = new AACTrackImpl(new FileDataSourceImpl( baseDir + "/aac_sample.aac" ));
    
    Movie movie = new Movie();
    movie.addTrack(h264Track);
    movie.addTrack(aacTrack);
    Container mp4file = new DefaultMp4Builder().build(movie);
    
    FileChannel fc = new FileOutputStream(new File(baseDir +"/output.mp4")).getChannel();
    mp4file.writeContainer(fc);
    fc.close();
    
    } catch (FileNotFoundException e) {
      e.printStackTrace();
      } catch (IOException e) {
       e.printStackTrace();
    }

**Comment by sannies** [comment]
If you have already a video I guess your source video is already an MP4.
Something like this:

Movie m = MovieCreator.create("Path to MP4");
List<Track> nuTracks = new ArrayList<>();

for (Track t : m.getTracks()) {
  // Re-use all tracks besides the audio track
  if (!"soun".equals(t.getHandler)) {
    nuTracks.add(t);
  }
}

Track nuAudio = new AACTrackImpl(new FileDatasourceImpl("path to raw AAC"));
nuTracks.add(nuAudio); // add the new audio track
m.setTracks(nuTracks);
Container c = new DefaultMp4Builder().build(m);
c.writeContainer(new FileOutputStream("path to result.mp4").getChannel());








2015-10-21 14:01 GMT+02:00 bhuvneshvarma <notifications@github.com>:

**Comment by sannies** [comment]
MP3 is MPEG-2 Layer 3. It is not officially supported by MPEG-4 and not
even specified in MP4 (MPEG-4 is the family of specifications / MP4 is one
specification basically making clear how AAC/AVC is transported in MPEG-4
containers). Only a few players can even play MP3 in MP4 containers. Don't
go there.
Convert your audio to AAC before. Don't use MP3 in 2015 - it is 20 years
old! (How old is your car?)

You are trying to open an MP3 track with the AACTrack class. That cannot
work and if you think about it you already know that.
There is a MP3TrackImpl but as I said: Don't go there! Convert your audio
to AAC.


2015-10-22 10:52 GMT+02:00 bhuvneshvarma <notifications@github.com>:

**Comment by bhuvneshvarma** [comment]
Can i programmatically covert mp3 to aac?Still mp3 is used widely..Most songs are in mp3 format..In my app i want user to select audio from his device and then replace that audio in a video..can i convert mp3 to AAC with this library ?

**Comment by bhuvneshvarma** [comment]
Thanks a lott!!For `aac` audio its working fine...
For `mp3` audios I tried replacing `AACTrackImpl` with `MP3TrackImpl` keeping rest of the above code same but still it gives me same exception `java.io.IOException: Expected Start Word 0x7ff`  ...Any idea why its not working?

**Comment by sannies** [comment]
I don't know much about MP3, the code expects 0x7ff as the first 11bits of
the file and it doesn't find these 11bits.
Is it really an mp3? Is it perhaps corrupt? is perhaps the assumption wrong
that a MP3 fiole always starts with these bits?


2015-10-22 13:09 GMT+02:00 bhuvneshvarma <notifications@github.com>:

**Comment by bhuvneshvarma** [comment]
I tried through different mp3 files and same exception..If you allow can i send you the mp3 audio file?

**Comment by sannies** [comment]
Send it and promise that you send me a huge donation once you become rich
by selling the app on the playstore.

2015-10-22 14:00 GMT+02:00 bhuvneshvarma <notifications@github.com>:

**Comment by bhuvneshvarma** [comment]
Sent on ur email..I am just a fresher in Android who is trying to learn . Thanku for the support!

**Comment by sannies** [comment]
I never used or tested the Mp3 stuff. It was contributed. The code does not
understand id3 tags and fails when it encounters it.
It's an easy fix, I'll quickly do it.

2015-10-22 15:03 GMT+02:00 bhuvneshvarma <notifications@github.com>:

**Comment by bhuvneshvarma** [comment]
Okay thanks..i'll wait for you to do that fix...

**Comment by sannies** [comment]
I uploaded version 1.1.15 to this
https://oss.sonatype.org/content/repositories/comgooglecodemp4parser-1084
 maven repository.
It muxes the files but I cannot playback the result but this is kind of
expected. MP3 in MP4 is not widely supported. Don't go there. If you want
that working you'll need to convert it to AAC.


2015-10-22 15:25 GMT+02:00 bhuvneshvarma <notifications@github.com>:

**Comment by bhuvneshvarma** [comment]
Okay thanks..I am using android studio and I am trying to add it as dependencies..What should i add for latest version as 'compile 'com.googlecode.mp4parser:isoparser:1.1.15'' is not working..Or do i need to download zip from github and add as module for latest version?

**Comment by sannies** [comment]
Your environment is your problem. You can download the jar from the url I
gave you - the rest is up to you.

2015-10-22 16:07 GMT+02:00 bhuvneshvarma <notifications@github.com>:

**Comment by bhuvneshvarma** [comment]
Okay ..Thanks a lott for ur support and such a nice library..

**Comment by bhuvneshvarma** [comment]
Files with extensions .m4a, .m4b, .m4p, .m4v, .m4r, .3gp, .mp4, .aac all are part of AAC. I tried with .m4a extension file and gave same error(java.io.IOException: Expected Start Word 0xfff)..Does it only support .aac extension file Or which all extensions in AAC coding it supports?

**Comment by sannies** [comment]
(1) m4a, .m4b, .m4p, .m4v, .m4r, .3gp, .mp4 is AAC in an MP4 container
(2) .aac is AAC ADTS format.

Use MovieCreator for (1)
Use AACTrackImpl for (2)

2015-10-22 16:43 GMT+02:00 bhuvneshvarma <notifications@github.com>:

**Comment by sunshinetpu** [comment]
@sannies Thank you very much for great support. But I got a problem. If the duration of video and new audio is not the same, I cannot seek when play the final video.

**Comment by priyankinfinnov** [comment]
Hey , 
bkjbkjbnkj687698698 can you share your code to merge acc audio with mp4 video.
I am finding a lot of trouble doing the same. Getting the same error as your "java.io.IOException: Expected Start Word 0xfff" but mne is not mp3 it is acc file. 
And what does sannies mean by raw acc ? (normal acc audio right ?)
my email id is mr.priyankagrawal@gmail.com

**Comment by sannies** [comment]
Raw AAC is typically AAC in ADTS packets. There are also other variants but
typically this the format when you have a file name [name].aac
Use mediainfo on the file. What does it show?

Grüße,
Sebastian

2016-01-08 20:34 GMT+01:00 Priyank Agrawal <notifications@github.com>:

**Comment by MikeAlbers23** [comment]
Hi sannies! I am new to GitHub and this is my first comment :)

I have successfully implemented this. The resulting mp4 file works perfectly on all Android devices and all Microsoft devices.

However there is 1 problem. The resulting file plays with No Sound on all Apple devices. When I explorer the file info on an Apple device, it appears to have trouble with the audio codec.

Step 1:
I create a MP4 video with my Android phone app and save it to my directory like normal.

Step 2:
I record a new audio file with this code:
        mRecorder = new MediaRecorder();
        mRecorder.setAudioSource(MediaRecorder.AudioSource.MIC);
        mRecorder.setOutputFormat(MediaRecorder.OutputFormat.AAC_ADTS);
        mRecorder.setOutputFile(directoryApp + mFileName_ACC);
        mRecorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);
        mRecorder.prepare(); // there is a try catch around this one
        mRecorder.start();
        // after recording for a few seconds, I do this
        mRecorder.stop();
        mRecorder.release();
        mRecorder = null;

Step 3:
I replace the audio file in the MP4 with this code:
        Movie movie = null;
        try {
            movie = MovieCreator.build(directoryApp + mFileName_MP4);
        } catch (IOException e) {
            e.printStackTrace();
        }
        List<Track> nuTracks = new ArrayList<>();
        for (Track track : movie.getTracks()) {
            // Re-use all tracks besides the audio track
            if (!"soun".equals(track.getHandler())) {
                nuTracks.add(track);
            }
        }
        try {
            Track nuAudio = new AACTrackImpl(new FileDataSourceImpl(directoryApp + mFileName_ACC));
            nuTracks.add(nuAudio); // add the new audio track
            movie.setTracks(nuTracks);
            Container mp4file = new DefaultMp4Builder().build(movie);
            FileChannel fc = new RandomAccessFile(directoryApp + mFileNameMP4, "rw").getChannel();
            mp4file.writeContainer(fc);
            fc.close();
        } catch (IOException e) {
            e.printStackTrace();
        }

I've researched the heck out of this, and am stuck!

I tested by adding all of the original nuTracks, including the soun (so basically just commented out the if(!"soun".equals... if statement), and skipping the part where I add in the nuAudio file. Those files do work on Apple devices.

I tested by creating an audio file directly from my built in Android voice recorder app. Still no sound on Apple devices.

I tested by creating an audio file directly from an Apple device, and the file types it would create were (.m4a and .amr). When I try to use those files instead of the .aac file I created, the error I get is this (java.io.IOException: Expected Start Word 0xfff), so I believe the mp4parser is requiring an AAC file type.

I am hoping you can help :)

Thank you,
Mike

**Comment by nguyen-tam** [comment]
> Hi sannies! I am new to GitHub and this is my first comment :)
> 
> I have successfully implemented this. The resulting mp4 file works perfectly on all Android devices and all Microsoft devices.
> 
> However there is 1 problem. The resulting file plays with No Sound on all Apple devices. When I explorer the file info on an Apple device, it appears to have trouble with the audio codec.
> 
> Step 1:
> I create a MP4 video with my Android phone app and save it to my directory like normal.
> 
> Step 2:
> I record a new audio file with this code:
> mRecorder = new MediaRecorder();
> mRecorder.setAudioSource(MediaRecorder.AudioSource.MIC);
> mRecorder.setOutputFormat(MediaRecorder.OutputFormat.AAC_ADTS);
> mRecorder.setOutputFile(directoryApp + mFileName_ACC);
> mRecorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);
> mRecorder.prepare(); // there is a try catch around this one
> mRecorder.start();
> // after recording for a few seconds, I do this
> mRecorder.stop();
> mRecorder.release();
> mRecorder = null;
> 
> Step 3:
> I replace the audio file in the MP4 with this code:
> Movie movie = null;
> try {
> movie = MovieCreator.build(directoryApp + mFileName_MP4);
> } catch (IOException e) {
> e.printStackTrace();
> }
> List nuTracks = new ArrayList<>();
> for (Track track : movie.getTracks()) {
> // Re-use all tracks besides the audio track
> if (!"soun".equals(track.getHandler())) {
> nuTracks.add(track);
> }
> }
> try {
> Track nuAudio = new AACTrackImpl(new FileDataSourceImpl(directoryApp + mFileName_ACC));
> nuTracks.add(nuAudio); // add the new audio track
> movie.setTracks(nuTracks);
> Container mp4file = new DefaultMp4Builder().build(movie);
> FileChannel fc = new RandomAccessFile(directoryApp + mFileNameMP4, "rw").getChannel();
> mp4file.writeContainer(fc);
> fc.close();
> } catch (IOException e) {
> e.printStackTrace();
> }
> 
> I've researched the heck out of this, and am stuck!
> 
> I tested by adding all of the original nuTracks, including the soun (so basically just commented out the if(!"soun".equals... if statement), and skipping the part where I add in the nuAudio file. Those files do work on Apple devices.
> 
> I tested by creating an audio file directly from my built in Android voice recorder app. Still no sound on Apple devices.
> 
> I tested by creating an audio file directly from an Apple device, and the file types it would create were (.m4a and .amr). When I try to use those files instead of the .aac file I created, the error I get is this (java.io.IOException: Expected Start Word 0xfff), so I believe the mp4parser is requiring an AAC file type.
> 
> I am hoping you can help :)
> 
> Thank you,
> Mike

Hi Mike, I have the same problem as you. How did you fix this one?

**Comment by aruproy** [comment]
@sannies Thank you so much for this great library. Your code snippet  
https://github.com/sannies/mp4parser/issues/121#issuecomment-149870813 works fine first time. However if I try to replace audio of the "result.mp4" again, 

                `Container c = new DefaultMp4Builder().build(m);`
is throwing this exception:

```
Exception:
length=417; index=417

StackTrace:
java.lang.ArrayIndexOutOfBoundsException: length=417; index=417

StackTraceDetails:
java.lang.ArrayIndexOutOfBoundsException: length=417; index=417
        at org.mp4parser.muxer.builder.DefaultMp4Builder.createStco(DefaultMp4Builder.java:509)
        at org.mp4parser.muxer.builder.DefaultMp4Builder.createStbl(DefaultMp4Builder.java:350)
        at org.mp4parser.muxer.builder.DefaultMp4Builder.createTrackBox(DefaultMp4Builder.java:311)
        at org.mp4parser.muxer.builder.DefaultMp4Builder.createMovieBox(DefaultMp4Builder.java:215)
        at org.mp4parser.muxer.builder.DefaultMp4Builder.build(DefaultMp4Builder.java:111) 
```
I have tested this on multiple MP4 videos with AAC audio. The length and index values are different but the crash is 100% reproducible. My Gradle settings: 
```
    implementation 'org.mp4parser:isoparser:1.9.41'
    implementation 'org.mp4parser:muxer:1.9.41'
```
Looking forward to hear from you. I would greatly appreciate your help.
