### ISSUE TITLE
Duration of output too short

### ISSUE THREAD

**Issue by redwoolf** [sannies/mp4parser#122]
I do this to create a muxed file from an AAC that is in an mp4 container and a raw h264 stream written to disk.

```
H264TrackImpl h264Track = new H264TrackImpl(new FileDataSourceImpl(videoFile), "eng", 25, 1);
Movie audio = MovieCreator.build(audioFile.getAbsolutePath());
audio.addTrack(h264Track);

Container mp4file = new DefaultMp4Builder().build(audio);
FileOutputStream fos = new FileOutputStream(new File(outputPath));
mp4file.writeContainer(fos.getChannel());
fos.close();
```

But when the file is opened in a player it only plays for a second before stopping. And the video player indicates that it is only 1 second long.

However, this is the ffprobe output on the muxed file:

```
aac @ 0x7f8eeb000000] Input buffer exhausted before END element found
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 't68618007':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42isom
    creation_time   : 2015-10-22 19:55:38
  Duration: 00:00:30.05, start: 0.000000, bitrate: 409 kb/s
    Stream #0:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2015-10-21 19:55:37
    Stream #0:1(eng): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p, 640x640, 6993 kb/s, 25 fps, 25 tbr, 25 tbn, 50 tbc (default)
    Metadata:
      creation_time   : 2015-10-22 19:55:38
      encoder         : AVC Coding
```

The mp4 audio file is clipped from an mp3 using this code: https://github.com/google/ringdroid/blob/master/src/com/ringdroid/soundfile/SoundFile.java

**Comment by sannies** [comment]
Hi Benjamin, 
ffprobe shows a duration of 30 seconds. What happens when you try ffplay? 
The message "Input buffer exhausted before END element found" might indicate that the data has not been written completely  (file truncated)
 Would you mind sending me an example file? 
I get quite a few requests and the overhead of getting projects to compile and execute is too big for me. 
Thanks,
Sebastian

**Comment by redwoolf** [comment]
This was being caused by me setting the frame rate too low in the encoded stream. Thanks for your response!
