### ISSUE TITLE
Appending videos with different bit encoding rate

### ISSUE THREAD

**Issue by bkjbkjbnkj687698698** [sannies/mp4parser#128]
Can i append videos with different encoding bit rate?

**Comment by sannies** [comment]
Yes you can as the bitrate is not the decisive factor. The decoding configuration (SPS/PPS) needs to be the same. If you don't know what this is have a look at profile/level: You can only append high@3.1 to high@3.1 (same level/profile is necessary, but not a sufficient condition!)

**Comment by bkjbkjbnkj687698698** [comment]
I ssent you two files on email with different bit encoding rate but other configuration same.I am not able to append it.Please check.Thamks!
