### ISSUE TITLE
Addressing of sample description in Sample To Group Box in moof

### ISSUE THREAD

**Issue by komar007** [sannies/mp4parser#129]
Hello,
I am not sure this is a bug (I might understand the spec improperly or there have been amendments or corrigenda), but I got the following exception when using isoviewer:
```
Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: Index: 65537, Size: 2
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.get(LinkedList.java:476)
	at com.googlecode.mp4parser.authoring.Mp4TrackImpl.getSampleGroups(Mp4TrackImpl.java:234)
	at com.googlecode.mp4parser.authoring.Mp4TrackImpl.<init>(Mp4TrackImpl.java:190)
	at com.googlecode.mp4parser.authoring.CencMp4TrackImplImpl.<init>(CencMp4TrackImplImpl.java:42)
	at com.github.sannies.isoviewer.IsoViewerFx.openFile(IsoViewerFx.java:89)
...
```
The problem seems to be here:
https://github.com/sannies/mp4parser/blob/master/isoparser/src/main/java/com/googlecode/mp4parser/authoring/Mp4TrackImpl.java#L234

According to ISO/IEC 14496-12:2012, 8.9.4:
>Zero or more SampleGroupDescription boxes may also be present in a Track Fragment Box. These
definitions are additional to the definitions provided in the Sample Table of the track in the Movie Box. Group definitions within a movie fragment can also be referenced and used from within that same movie fragment.

> Within the SampleToGroup box in that movie fragment, the group description indexes for groups defined within the same fragment start at 0x10001, i.e. the index value 1, with the value 1 in the top 16 bits. This means there must be fewer than 65536 group definitions for this track and grouping type in the sample table in the Movie Box.

It seems that the index 65537 which is trying to be addressed should be interpreted as 1 instead of 65537.

I generated a file which reproduces the (potential) issue:
http://space.komar.be/out0_002.mp4

Best Regards,
Michał

**Comment by sannies** [comment]
Hi Michał,
Thanks for bringing this to my attention. I've always overread this part but must admit that I've seen 65537 as sample description index already but never concluded that this is something I have to deal with. https://github.com/sannies/mp4parser/commit/44e6f24ff8713416dbfd6266d56b48fa050236e1 fixes the problem. 
I made  published a release to a staging repo at https://oss.sonatype.org/content/repositories/comgooglecodemp4parser-1086 for you to test. 
Grüße,
Sebastian

**Comment by komar007** [comment]
Thank you.
That's very helpful, as always.

Best,
Michał
