### ISSUE TITLE
MP4 Hinting

### ISSUE THREAD

**Issue by NitroG42** [sannies/mp4parser#131]
Hello, I have problem making a MP4 playable by Android, and found after some research :  http://stackoverflow.com/a/13432650/702229
That my MP4 require to be hinted for rtp. 
Basically : if create a mp4 (using simple implementation with H264TrackImpl, Movie and DefaultMp4Builder), it can't be read by most basic players. If I send the mp4 to my computer, use **MP4Box -hint** on it, and send it back, it can be played.
Do you have any hint (sorry) on how i could do that programmatically with MP4Parser ?

Here's my code : 
```java
H264TrackImpl h264Track = new H264TrackImpl(new FileDataSourceImpl(h264File), "fre", fps * 1000, 1001);
Movie video = new Movie();
video.addTrack(h264Track);
Container container = new DefaultMp4Builder().build(video);
FileOutputStream fos = new FileOutputStream(VideoUtils.getVideoFile(name));
```
The H264 file is a h264 stream that a get from a device remotely, so I write it directly to a file and it seems to work... But not with all player.
Btw here the difference between a non-hinted file and a hinted one :
Non-hinted :
```
* Movie Info *
	Timescale 20000 - Duration 00:00:00.000
	1 track(s)
	Fragmented File: yes - duration 00:00:08.208
3 fragments - 0 SegmentIndexes
	File suitable for progressive download (moov before mdat)
	File Brand isom - version 0
	Created: GMT Thu Nov  5 10:18:06 2015
	Modified: GMT Thu Nov  5 10:18:06 2015

File has no MPEG4 IOD/OD


Track # 1 Info - TrackID 1 - TimeScale 20000 - Media Duration 00:00:00.000
Media Info: Language "fre (fre)" - Type "vide:avc1" - 0 samples
Fragmented track: 164 samples - Media Duration 00:00:08.208
Visual Track layout: x=0 y=0 width=640 height=480
MPEG-4 Config: Visual Stream - ObjectTypeIndication 0x21
AVC/H264 Video - Visual Size 640 x 480
	AVC Info: 1 SPS - 1 PPS - Profile Baseline @ Level 3
	NAL Unit length bits: 32
	SPS#1 hash: F933009D14E06BC9AFD216B12347E10D504E1383
	PPS#1 hash: DE5CCFB17A950D17385F1511EA12D0A3E9F024C7
Self-synchronized
	RFC6381 Codec Parameters: avc1.42001e
	No sync sample found
```

hinted :
```
* Movie Info *
	Timescale 20000 - Duration 00:00:08.208
	2 track(s)
	Fragmented File: no

	File suitable for progressive download (moov before mdat)
	File Brand isom - version 0
	Created: GMT Thu Nov  5 10:18:06 2015
	Modified: GMT Thu Nov  5 10:18:06 2015

File has no MPEG4 IOD/OD
1 UDTA types: hnti (1) 

Track # 1 Info - TrackID 1 - TimeScale 20000 - Media Duration 00:00:08.208
Media Info: Language "fre (fre)" - Type "vide:avc1" - 164 samples

Visual Track layout: x=0 y=0 width=640 height=480
MPEG-4 Config: Visual Stream - ObjectTypeIndication 0x21
AVC/H264 Video - Visual Size 640 x 480
	AVC Info: 1 SPS - 1 PPS - Profile Baseline @ Level 3
	NAL Unit length bits: 32
	SPS#1 hash: F933009D14E06BC9AFD216B12347E10D504E1383
	PPS#1 hash: DE5CCFB17A950D17385F1511EA12D0A3E9F024C7
Self-synchronized
	RFC6381 Codec Parameters: avc1.42001e
	Average GOP length: 32 samples

Track # 2 Info - TrackID 65536 - TimeScale 90000 - Media Duration 00:00:08.208
Media Info: Language "und (und)" - Type "hint:rtp " - 164 samples
1 UDTA types: hnti (1) 
Streaming Hint Track for track ID 1
	RFC6381 Codec Parameters: rtp 
	Average GOP length: 32 samples
```

Thank you very much for your help.

**Comment by sannies** [comment]
Hi Nitro,
in my experience most players will play back the file. I can see that my
code doesn't mark any I-frames as sync samples "No sync sample found" that
is a problem which typically doesn't happen. Please make a raw h264 file
available for me to check what's not working with the I-frame detection.
Hinting for RTP streaming is not what's repairing the file. The actual
hinting doesn't make the file playable - the mp4box command simple
understands the MP4 file and rewrites it in its own specific way and
regenerates the sync sample information. The hint track that is generally
is not read by any players - it is meant for old-school RTMP streaming
servers.

Grüße,
Sebastian


2015-11-05 11:49 GMT+01:00 NitroG42 <notifications@github.com>:

**Comment by NitroG42** [comment]
Here's the raw h264file : https://www.dropbox.com/s/2sw88b72rpi7gs0/test.h264?dl=0
And the generated file (just in case) : https://www.dropbox.com/s/ggldr8cop6uc71l/test.mp4?dl=0
Thanks for looking at it.

**Comment by NitroG42** [comment]
Forgot something important : I'm using the maven version of MP4Parser, so it's on1.1.14 . I'll try the 1.1.17 version right now.

**Comment by sannies** [comment]
The video is working when I mux it with this code:

Movie v = new Movie(); // =
MovieCreator.build("C:\\dev\\DRMTODAY-872\\31245689abb7c52a3d0721447bddd6cd_Tears_Of_Steel_600000.mp4");
Track audio = new H264TrackImpl(new
FileDataSourceImpl("C:\\Users\\sannies\\Downloads\\test.h264"));
v.addTrack(audio);

Mp4Builder defaultMp4Builder = new DefaultMp4Builder();
Container c = defaultMp4Builder.build(v);
c.writeContainer(new FileOutputStream("output.mp4").getChannel());

https://drive.google.com/file/d/0B4V1tYh3puArRGdQX3FIYmxYRkU/view?usp=sharing

So I'm not 100% sure where the problem is. A bug in 1.1.14 I'm not aware
of? 1.1.17 seems to work

2015-11-05 14:15 GMT+01:00 NitroG42 <notifications@github.com>:

**Comment by NitroG42** [comment]
Yeah it works ! the difference is that a create a mp4 from nothing :
Movie video = new Movie();

So I need to have add the track to a base mp4 file that I should add to my app ?
What does "DRMTODAY-872\\31245689abb7c52a3d0721447bddd6cd_Tears_Of_Steel_600000.mp4" contains ?

**Comment by sannies** [comment]
It's just a comment. No active code, it's a left-over from previous local
tests

2015-11-05 17:30 GMT+01:00 NitroG42 <notifications@github.com>:

**Comment by NitroG42** [comment]
Ok, it had nothing to do with that. The problem was the naming of both file.
I was using the date formatted in that way : "EEE dd MM yy HH:mm:ss" which give : "jeu. 05 11 15 14:32:22.mp4"
Why you might say ? Well because I'm obviously stupid...
Using simple file name, it works. But i really don't understand why because as you saw the file created does works on some player.
