### ISSUE TITLE
Can't find .jar libraries 

### ISSUE THREAD

**Issue by Taiko3615** [sannies/mp4parser#133]
Sorry. Newb question here.

Where can I find the jar libraries ? The release zip I found doesn't contain any jars https://github.com/sannies/mp4parser/releases/tag/mp4parser-project-1.1.17

**Comment by jghazarian** [comment]
You can always grab a jar directly from Maven. http://repo1.maven.org/maven2/com/googlecode/mp4parser/isoparser/

**Comment by Taiko3615** [comment]
Exactly what I was looking for !!! Thanks !
