### ISSUE TITLE
Get Progress of Movie File being written

### ISSUE THREAD

**Issue by krazykira** [sannies/mp4parser#138]
I am writing a movie file like this 
```
	Container out = new DefaultMp4Builder().build(finalMovie);
	FileChannel fc = new RandomAccessFile(finalVideoFile, "rw").getChannel();
	out.writeContainer(fc);
	fc.close();
```
I can see the `L0ogcat` and it shows progress of file being written (in `MBs`) 
So i am wondering. is there a way to get Progress of file being written?
Or  
Can i sequentially write a `movie` object like we write  `MultiPartForm Request` ?

**Comment by sannies** [comment]
There is no callback and the log is just for the mdat box. I'd propose to
get the filesize by iterating over all boxes in the root container and add
up their getSize(). Then you can implement something like a CountingChannel
to keep track of how much you've written or you might even poll the
filesize.

Best Regards,
Sebastian

2015-11-12 5:44 GMT+01:00 Sheraz Ahmad Khilji <notifications@github.com>:

**Comment by krazykira** [comment]
@sannies  how do you propose i implement a Counting Channel or POLL the `File Channel` for how much amount of data has been written ?

**Comment by sannies** [comment]
Depends on what you like.
Checking every few seconds the file size might be an option suitable for
you if you have a second thread.
Or in case you need active notification of the progress bar is better for
you could implement a WritableByteChannel that counts the bytes written and
proxies to the actual WritableByteChannel?


2015-11-12 11:00 GMT+01:00 Sheraz Ahmad Khilji <notifications@github.com>:

**Comment by krazykira** [comment]
Thanks this is how i ended up doing it.
In My `Asynctask` `doInBackground()` method where movie` file was being written i started a `thread` like you said which monitored the size of the file and provided updates about how much merging was done. For more details please see the code below
```

			Container out = new DefaultMp4Builder().build(finalMovie);

			FileChannel fc = new RandomAccessFile(finalVideoFile, "rw")
					.getChannel();
			for (int i = 0; i < out.getBoxes().size(); i++) {
				finalVideoFileSize += out.getBoxes().get(i).getSize();
			}
			Thread t=new Thread(new Runnable() {

				@Override
				public void run() {

					Log.e("VideoMerge", "Started");
					long currentFileSize = 0;
					if (finalVideoFile.exists())
						currentFileSize = finalVideoFile.length();
					while (finalVideoFileSize != currentFileSize) {
						try {
							Thread.sleep(5000);
						} catch (InterruptedException e) {
							e.printStackTrace();
						}
						if (finalVideoFile.exists()) {
							currentFileSize = finalVideoFile.length();
							Log.e("VideoMerge", "Total: " + finalVideoFileSize
									+ " current: " + currentFileSize);
							int progress = (int) (currentFileSize * 100 / finalVideoFileSize);
							publishProgress(progress);
						}

					}
					Log.e("VideoMerge", "Ended");

				}
			});
			t.start();

			out.writeContainer(fc);
			t.stop();
			fc.close();
```

this code can also be seen [here](https://github.com/krazykira/CuXtomCam/blob/develop/CuXtom%20Cam%20Library/src/com/glass/cuxtomcam/VideoMerger.java#L103)
