### ISSUE TITLE
Any Licence require to use this library in my Android application?

### ISSUE THREAD

**Issue by testsoft49** [sannies/mp4parser#150]
Can i use this library in my application, is it available free ? Or any licence or approval require ?

**Comment by sannies** [comment]
There is a [LICENSE](https://raw.githubusercontent.com/sannies/mp4parser/master/LICENSE)
file in the root folder and it contains the text of the Apache License 2.0. 
I'm not giving any advice on the license. You'll need to figure out by yourself if it is usable for you.
