### ISSUE TITLE
IndexOutOfBoundsException on DefaultMp4Builder().build()

### ISSUE THREAD

**Issue by flieks** [sannies/mp4parser#153]
Hi,

java.lang.IndexOutOfBoundsException

on this line
BasicContainer out = (BasicContainer) new DefaultMp4Builder().build(videoNew);

stacktrace:
java.util.AbstractList.subList(AbstractList.java:738)
com.googlecode.mp4parser.authoring.tracks.CroppedTrack.getSamples(CroppedTrack.java:63)
com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.build(DefaultMp4Builder.java:98)

(only when i add m4a audio to another mp4)
i checked and paths are good 
/data/data/com.telerik.CatWalk/files/featherlike.m4a
/data/data/com.telerik.CatWalk/files/1wXVM20160118_133746.mp4

strange this is: sometimes it works, sometimes it doesn't.
I also puted the video in slow motion..

Greetings

**Comment by sannies** [comment]
You will need to make the files available to me and show a bit more of your
code - otherwise it's really hard for me to assess the problem

2016-01-18 14:46 GMT+02:00 De Lille Felix <notifications@github.com>:
