### ISSUE TITLE
Mp4 mime type files

### ISSUE THREAD

**Issue by kuginga** [sannies/mp4parser#159]
I'm using the new version of its library to cut mp4 files in Android. With earlier versions did not have problems, but with the latter, the MIME type that arrives at the server is application/octet-stream. That I can do to get the MIME type video / mp4? ... I have you lost a couple of days with this, help me ??? ...
Thanks for everything and thank you for his splendid work.

**Comment by sannies** [comment]
Hi,
it's not my code that determines the mime type. It's your HTTP client that sets the 'Content-Type' header. 
The container can be written like this:

        Container c2 = new FragmentedMp4Builder().build(m);
        c2.writeContainer(new FileOutputStream("b.mp4").getChannel());

**Comment by kuginga** [comment]
Thank you very much for your quick response. Try to go out there, but I've tried things in that sense ... the problem is that if you upload a video uncut not change the mime, it only where short videos ... Thank you

Date: Thu, 11 Feb 2016 03:44:42 -0800
