### ISSUE TITLE
mp4Parse is unavailable on JitPack.io

### ISSUE THREAD

**Issue by Pirksy** [sannies/mp4parser#168]
Error:A problem occurred configuring project ':app'.
> Could not find mp4parser.aar (com.github.sannies:mp4parser:mp4parser-project-1.9.27).
  Searched in the following locations:
      https://jitpack.io/com/github/sannies/mp4parser/mp4parser-project-1.9.27/mp4parser-mp4parser-project-1.9.27.aar

**Comment by sannies** [comment]
??? What do you want me to do? What is an .aar file?
