### ISSUE TITLE
Cut and merge mp4

### ISSUE THREAD

**Issue by Pirksy** [sannies/mp4parser#172]
Hello, I'm trying to cut each video and merge them,  I'm using this method 
`private void cutAndJoin(List<File> parts, File outFile) throws IOException {

        Movie movie = new Movie();
        movie.setTracks(new LinkedList<Track>());

        List<CroppedTrack> croppedTrackList = new ArrayList<>();

        List<Movie> inMovies = new ArrayList<Movie>();
        for (File videoUri : parts) {
            inMovies.add(MovieCreator.build(videoUri.getAbsolutePath()));
        }
        for (int m = 0; m < inMovies.size(); m++) {
            
            double startTime1 = 10;
            double endTime1 = 15;

            boolean timeCorrected = false;

            for (Track track : inMovies.get(m).getTracks()) {
                if (track.getSyncSamples() != null && track.getSyncSamples().length > 0) {
                    if (timeCorrected) {
                        throw new RuntimeException("The startTime has already been corrected by another track with SyncSample. Not Supported.");
                    }
                    startTime1 = correctTimeToSyncSample(track, startTime1, false);
                    endTime1 = correctTimeToSyncSample(track, endTime1, true);
                    timeCorrected = true;
                }
            }

            for (Track track : inMovies.get(m).getTracks()) {
                long currentSample = 0;
                double currentTime = 0;
                double lastTime = -1;
                long startSample1 = -1;
                long endSample1 = -1;

                for (int i = 0; i < track.getSampleDurations().length; i++) {
                    long delta = track.getSampleDurations()[i];

                    if (currentTime > lastTime && currentTime <= startTime1) {
                        startSample1 = currentSample;
                    }
                    if (currentTime > lastTime && currentTime <= endTime1) {
                        endSample1 = currentSample;
                    }

                    lastTime = currentTime;
                    currentTime += (double) delta / (double) track.getTrackMetaData().getTimescale();
                    currentSample++;
                }
                croppedTrackList.add(new CroppedTrack(track, startSample1, endSample1));
            }
        }
        CroppedTrack[] croppedTracks = croppedTrackList.toArray(new CroppedTrack[croppedTrackList.size()]);
        movie.addTrack(new AppendTrack(croppedTracks));
        Container out = new DefaultMp4Builder().build(movie);
        FileChannel fc = new RandomAccessFile(outFile, "rw").getChannel();
        out.writeContainer(fc);
        fc.close();
    }`

each video's duration is 20 sec, but I'm getting an error 
`Cannot merge VisualSampleEntry[AvcConfigurationBox{avcDecoderConfigurationRecord=AvcDecoderConfigurationRecord{configurationVersion=1, avcProfileIndication=66, profileCompatibility=192, avcLevelIndication=40, lengthSizeMinusOne=3, hasExts=false, chromaFormat=-1, bitDepthLumaMinus8=-1, bitDepthChromaMinus8=-1, lengthSizeMinusOnePaddingBits=63, numberOfSequenceParameterSetsPaddingBits=7, chromaFormatPaddingBits=31, bitDepthLumaMinus8PaddingBits=31, bitDepthChromaMinus8PaddingBits=31}};com.googlecode.mp4parser.boxes.apple.PixelAspectRationAtom@cc37d36] and AudioSampleEntry{bytesPerSample=0, bytesPerFrame=0, bytesPerPacket=0, samplesPerPacket=0, packetSize=0, compressionId=0, soundVersion=0, sampleRate=48000, sampleSize=16, channelCount=1, boxes=[com.googlecode.mp4parser.boxes.mp4.ESDescriptorBox@122]}]
02-29 19:14:46.838 27907-2455/com.android.minivideomaker W/System.err: java.io.IOException: Cannot merge VisualSampleEntry[AvcConfigurationBox{avcDecoderConfigurationRecord=AvcDecoderConfigurationRecord{configurationVersion=1, avcProfileIndication=66, profileCompatibility=192, avcLevelIndication=40, lengthSizeMinusOne=3, hasExts=false, chromaFormat=-1, bitDepthLumaMinus8=-1, bitDepthChromaMinus8=-1, lengthSizeMinusOnePaddingBits=63, numberOfSequenceParameterSetsPaddingBits=7, chromaFormatPaddingBits=31, bitDepthLumaMinus8PaddingBits=31, bitDepthChromaMinus8PaddingBits=31}};com.googlecode.mp4parser.boxes.apple.PixelAspectRationAtom@cc37d36] and AudioSampleEntry{bytesPerSample=0, bytesPerFrame=0, bytesPerPacket=0, samplesPerPacket=0, packetSize=0, compressionId=0, soundVersion=0, sampleRate=48000, sampleSize=16, channelCount=1, boxes=[com.googlecode.mp4parser.boxes.mp4.ESDescriptorBox@122]}
` 
Could you tell me please what I'm doing wrong

**Comment by ml-bright** [comment]
how to solve this problem?

**Comment by Pirksy** [comment]
There is a problem with short videos. Use ffmpeg library
