### ISSUE TITLE
Change video resolution from [sourceWidth, sourceHeight] to [destWidth, destHeight] 

### ISSUE THREAD

**Issue by neestell** [sannies/mp4parser#176]
Hi, I cannot find an example for mp4parser to change a video [width;height] to lower size. Please let me know how todo it with your library if possible.
Thanks

**Comment by sannies** [comment]
This requires a re-encode of the content and is mp4parser-wise out of scope

2016-03-02 10:09 GMT+02:00 neestell <notifications@github.com>:

**Comment by neestell** [comment]
Thanks a lot!

**Comment by chnouman** [comment]
@neestell any solution that you had found for this?
