### ISSUE TITLE
How to add animations like transitions in between videos while merging videos?

### ISSUE THREAD

**Issue by AbhishekPantUK** [sannies/mp4parser#181]

**Comment by sannies** [comment]
By creating them and putting them in between? Or are you asking for algorithms to visually merge videos? Anyways this is not doable with the mp4parser as it is about generating videos from videos and not about MP4 containers.

**Comment by AbhishekPantUK** [comment]
I want to do 'creating them and putting them in between'? If not possible can you please suggest me how to achieve that.

**Comment by sannies** [comment]
1. Use MediaCodec API to create actual bitmaps from last frames of the
first video and from the first frames of the later video
2. Do whatever you like with these bitmap - merge them, overlay them - it's
up to you how you'd like to do it.
3. Now use the MediaCodec API to generate a video from the bitmaps
generated in step 2.
4. Then you might use the mp4parser to append 1st vid + generated vid + 2nd
vid



2016-03-11 9:22 GMT+02:00 AbhishekPantUK <notifications@github.com>:

**Comment by AbhishekPantUK** [comment]
Thanks for your help, I'll try it.
