### ISSUE TITLE
Multiple JPG images to mp4 video file.

### ISSUE THREAD

**Issue by zukopvd** [sannies/mp4parser#182]
Hi!
Is there any sample code to convert multiple JPG files into a video file with mp4parser on Android?

**Comment by sannies** [comment]
Hi Whateveryournameis, 

MP4 is a container format - the mp4parser deals with the container and typically not with the compression of pictures itself. What you are trying to do typically involves re-encoding of jpegs with a video compression codec such as H264. You might want to try to use Motion JPEG - a rather old and inefficient format but it might suit your needs. 
Steps you should take: 
1. Verify that MJPEG works for you by using ffmpeg and produce a mjpeg clip from you images
2. If that works you'll need to look at https://github.com/sannies/mp4parser/blob/master/muxer/src/main/java/org/mp4parser/muxer/tracks/mjpeg/OneJpegPerIframe.java and modify according to your needs. The heavy lifting is already done.
