### ISSUE TITLE
Wrong maven dependency on Readme.md?

### ISSUE THREAD

**Issue by javimolla** [sannies/mp4parser#188]
The Readme.md points to a dependency that does not match the current source code. Now it's pointing to [com.googlecode.mp4parser](http://mvnrepository.com/artifact/com.googlecode.mp4parser) while the right seems to be [org.mp4parser](http://mvnrepository.com/artifact/org.mp4parser)

**Comment by david120911** [comment]
compile 'org.mp4parser:isoparser:1.9.27'
    compile 'org.mp4parser:muxer:1.9.27'
    compile 'org.mp4parser:streaming:1.9.27'     in build.gradle solve this problem
