### ISSUE TITLE
Get value 0 unless I get flags ?

### ISSUE THREAD

**Issue by tgourdel** [sannies/mp4parser#197]
Hello,

I noticed that when I am doing a get of an attribute : 

```
System.out.print("Track ID : "+tfhd.getTrackId());
```

I got value 0 which is not correct.

But when I run : 

```
System.out.print("Flags : "+tfhd.getFlags());
System.out.print("Track ID : "+tfhd.getTrackId());
```

I got flags and the correct Track ID ...

Any idea ?

Thank you

**Comment by sannies** [comment]
That is weird. Are you using a released version? Or did you compile on your
own? Parsing of the data is only done once you access a getter by an
'aspect'  so if you'd compile it on your own you'd need to make sure that
the aspectj compiler is executed as well. The behavior you describe looks a
bit like the aspect itself is not executed until  the getFlags is called.

Thibaut G. <notifications@github.com> schrieb am Di., 24. Mai 2016 um
15:26 Uhr:

**Comment by tgourdel** [comment]
Thank you for your answer,

I clone from master branch and I import in eclipse as an existing maven project. Building is ok 
How can I make sure the aspectj compiler is executed ? In the isoparser pom.xml it appears but I have done nothing special.

Thanks

**Comment by sannies** [comment]
Sorry but as I publish releases I don't see the point supporting individual
compile problems in environments I don't even use.
Please use a release! They are published to maven central.

Thibaut G. <notifications@github.com> schrieb am Do., 26. Mai 2016 um
10:59 Uhr:

**Comment by tgourdel** [comment]
You're right ! 
Thank you
