### ISSUE TITLE
Android - sample duration is wrong, can it be changed?

### ISSUE THREAD

**Issue by cybaker** [sannies/mp4parser#201]
There's a new issue with recording for Android on some devices with Marshmallow. It is a know issue apparently and is slated to be fixed at some point, involving Marshmallow's new deep sleep mode.

As a fix, I'm looking into using mp4parser to rewrite the first recorded sample's duration, which is the problem. As seen in the attachments (1 good recording, 1 bad recording), using mp4parser, the first sample's decoding time is huge when the problem occurs.

Is there an easy way to change that number 88813322 to 3322, which is the right number (it does vary, but is close to the other numbers and shouldn't make much of a difference)? For instance, I can getSampleDurations(), but I cannot setSampleDurations() from an Mp4TrackImpl. I do see the fragment mp4 has a setSampleDuration() method but don't know if I can use a fragment mp4.

<img width="411" alt="screen shot 2016-06-02 at 7 32 06 am" src="https://cloud.githubusercontent.com/assets/1371616/15760158/d4942c7a-28c6-11e6-95db-ea27c3090627.png">
<img width="411" alt="screen shot 2016-06-02 at 7 51 37 am" src="https://cloud.githubusercontent.com/assets/1371616/15760159/d495f0a0-28c6-11e6-9ab6-4269211e1cf2.png">

**Comment by sannies** [comment]
Hi,
this is something I wouldn't do by creating a movie/track object. I'd open
the file with new IsoFile("file"), navigate to the time to sample box with
a Path expression and correct these values directly.
Best Regards,
Sebastian


Tom <notifications@github.com> schrieb am Do., 2. Juni 2016 um 22:35 Uhr:

**Comment by cybaker** [comment]
Absolutely worked with that hint. I corrected the value, then wrote out the container as such:
                Movie movie = CustomMovieCreator.build(rawFile.getAbsolutePath()); // fix first sample
                Container out = new DefaultMp4Builder().build(movie);
                FileChannel fc = new RandomAccessFile(file, "rw").getChannel();
                out.writeContainer(fc);
                fc.close();
