### ISSUE TITLE
Is it possible to use this library for reversing videos?

### ISSUE THREAD

**Issue by ahmetcj4** [sannies/mp4parser#210]

**Comment by sannies** [comment]
Hi,
no this is not possible. Reversing requires re-encoding. Pictures within typical videostreams such as H264 have references to other frames. Very simplified something like: To render the current frame the decoder is instructed to use parts of the previous frame. While it is even a feature of H264 to reference future frames you'd to change a whole lot in the actual H264 data stream. That is nothing an MP4 level (==Container level) tool can do. 
Best Regards,
Sebastian

**Comment by ahmetcj4** [comment]
@sannies thank you for your comment. Do you know any other library or tool that I can use to reverse videos?
Thamks,
Ahmet

**Comment by sannies** [comment]
you can most likely do that with ffmpeg. I don't how but the brute force approach would to generate 1 PNG per frame (stills), reverse the numbers with a script and then encode the video from the stills.
