### ISSUE TITLE
java.lang.RuntimeException: A cast to int has gone wrong. Please contact the mp4parser discussion group (3317973711)

### ISSUE THREAD

**Issue by liyzay** [sannies/mp4parser#211]
> Exception in thread "main" java.lang.RuntimeException: A cast to int has gone wrong. Please contact the mp4parser discussion group (3317973711)
	at com.googlecode.mp4parser.util.CastUtils.l2i(CastUtils.java:30)
	at com.googlecode.mp4parser.AbstractBox.parse(AbstractBox.java:110)
	at com.coremedia.iso.AbstractBoxParser.parseBox(AbstractBoxParser.java:107)
	at com.googlecode.mp4parser.BasicContainer.next(BasicContainer.java:185)
	at com.googlecode.mp4parser.BasicContainer.hasNext(BasicContainer.java:161)
	at com.googlecode.mp4parser.util.LazyList.blowup(LazyList.java:30)
	at com.googlecode.mp4parser.util.LazyList.size(LazyList.java:77)
	at com.googlecode.mp4parser.BasicContainer.getBoxes(BasicContainer.java:80)
	at com.googlecode.mp4parser.authoring.samples.DefaultMp4SampleList.<init>(DefaultMp4SampleList.java:36)
	at com.coremedia.iso.boxes.mdat.SampleList.<init>(SampleList.java:33)
	at com.googlecode.mp4parser.authoring.Mp4TrackImpl.<init>(Mp4TrackImpl.java:64)
	at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:57)
	at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:38)
	at alex.liyzay.demo.ExampleTest.printMovieInfo(ExampleTest.java:107)
	at alex.liyzay.demo.ExampleTest.main(ExampleTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**I got this exception when I`m trying to print info about a movie which I have replaced its audio with mp4parser.**

Here`s my codes:

	static void printMovieInfo(String path){
		try {
			Movie movie = MovieCreator.build(path);
			for (Track track:movie.getTracks()){
				System.out.println(track.getHandler());
				System.out.println(trackDuration(track));
			}
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	static double trackDuration(Track track){
		return (double)track.getDuration() / track.getTrackMetaData().getTimescale() ;
	}

	static void muxAudioVideo(String videoPath,String audioPath,String outputPath){
		try {
			Movie movie = MovieCreator.build(videoPath);
			Movie outMovie = new Movie();
			int videoDuration=0;
			for (Track track:movie.getTracks()){
				if("vide".equals(track.getHandler())){
					outMovie.addTrack(track);
					videoDuration = (int) Math.ceil(trackDuration(track));
				}
			}
			System.out.println("videoDuration:"+videoDuration);

			AACTrackImpl audioTrack = new AACTrackImpl(new FileDataSourceImpl(audioPath));
			int audioDuration = (int) Math.ceil(trackDuration(audioTrack));
			System.out.println("audioDuration:"+audioDuration);

			if(audioDuration<videoDuration){
				double exactlyDuration = (double) videoDuration / audioDuration ;
				int minDuration = (int) Math.floor(exactlyDuration);
				double offsetDuration = exactlyDuration - minDuration ;
				Track[] audioTracks = new Track[minDuration+1];
				for (int i=0;i<minDuration;i++){
					audioTracks[i] = audioTrack ;
				}
				int offsetSize = (int) (audioTrack.getSamples().size()* offsetDuration);
				audioTracks[minDuration] = new CroppedTrack(audioTrack,0,offsetSize);
				outMovie.addTrack(new AppendTrack(audioTracks));
			}else if(audioDuration>videoDuration){
				double offsetDuration = (double) videoDuration / audioDuration ;
				int offsetSize = (int) (audioTrack.getSamples().size()* offsetDuration);
				CroppedTrack croppedTrack = new CroppedTrack(audioTrack,0,offsetSize);
				outMovie.addTrack(croppedTrack);
			}else {
				outMovie.addTrack(audioTrack);
			}

			Container container = new DefaultMp4Builder().build(outMovie);
			File outFile = new File(outputPath);
			RandomAccessFile randomAccessFile = new RandomAccessFile(outFile,"rw");
			container.writeContainer(randomAccessFile.getChannel());
			randomAccessFile.close();

		} catch (IOException e) {
			e.printStackTrace();
		}
	}

**Comment by liyzay** [comment]
This exception only happens on android phone,It works fine on desktop.
Maybe it have some problem with the android frameworks?

**Comment by Praveen123S** [comment]
private String increaseAudio(long value,String path) {
        File firstFile=new File(Environment.getExternalStorageDirectory().getAbsolutePath() + "/" + Constants.PROJECT_FOLDER + "/Sounds/"+path+ ".mp3");

        System.out.println("paths "+path);
        System.out.println("paths2 "+firstFile.getAbsolutePath());
        Movie movieA = null;
        try {
            movieA = MovieCreator.build(firstFile.getAbsolutePath());
        } catch (IOException e) {
            e.printStackTrace();
        }
        final Movie finalMovie = new Movie();
        List<Track> audioTracks = new ArrayList<>();
        ArrayList<Movie> movilist=new ArrayList<>();
        for(int i=0;i<value;i++){
            movilist.add(movieA);
        }

        for (Movie movie : movilist) {
            for (Track track : movie.getTracks()) {
                if (track.getHandler().equals("soun")) {
                    audioTracks.add(track);
                }
            }
        }
        try {
            finalMovie.addTrack(new AppendTrack(audioTracks.toArray(new Track[audioTracks.size()])));
        } catch (IOException e) {
            e.printStackTrace();
        }

        final Container container = new DefaultMp4Builder().build(finalMovie);
        File mergedFile = new File(Environment.getExternalStorageDirectory().getAbsolutePath() + "/" + Constants.PROJECT_FOLDER + "/Sounds/newsound123" + ".mp3");
        try {
            final FileOutputStream fos = new FileOutputStream(mergedFile);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        FileChannel fc = null;
        try {
            fc = new RandomAccessFile(mergedFile, "rw").getChannel();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        try {
            container.writeContainer(fc);
        } catch (IOException e) {
            e.printStackTrace();
        }
        try {
            fc.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return mergedFile.getAbsolutePath();
    }

**Comment by Praveen123S** [comment]
not working proper....................................
