### ISSUE TITLE
Simple audio track tests are giving strange parse errors 

### ISSUE THREAD

**Issue by gbildson** [sannies/mp4parser#25]
I'm getting these kinds of exceptions from various test programs.  From trying to debug the issue, I get very strange behavior with the bit alignment when trying to read the audio files.  
<pre>Exception in thread "main" java.io.IOException: Expected Start Word 0xfff
	at com.googlecode.mp4parser.authoring.tracks.AACTrackImpl.readADTSHeader(AACTrackImpl.java:293)
	at com.googlecode.mp4parser.authoring.tracks.AACTrackImpl.readSamples(AACTrackImpl.java:325)
	at com.googlecode.mp4parser.authoring.tracks.AACTrackImpl.<init>(AACTrackImpl.java:142)
	at com.googlecode.mp4parser.authoring.tracks.AACTrackImpl.<init>(AACTrackImpl.java:135)
</pre>

I initially received a similar error with an mp3 test:
<pre>
Exception in thread "main" java.io.IOException: Expected Start Word 0x7ff
	at com.googlecode.mp4parser.authoring.tracks.MP3TrackImpl.readMP3Header(MP3TrackImpl.java:200)
	at com.googlecode.mp4parser.authoring.tracks.MP3TrackImpl.readSamples(MP3TrackImpl.java:175)
	at com.googlecode.mp4parser.authoring.tracks.MP3TrackImpl.<init>(MP3TrackImpl.java:64)
	at com.googlecode.mp4parser.authoring.tracks.MP3TrackImpl.<init>(MP3TrackImpl.java:53)
	at Greg2.main(Greg2.java:26)
</pre>

and it seemed that making test changes to the MP3TrackImpl.java class after the code causing the problem would affect earlier code.   For example, if I commented out the line:
<pre>
        hdr.layer = brb.readBits(2); // C
</pre>

The code would make it past the above code.   

I was also playing around  with the bits coming back from the line:
<pre>
        BitReaderBuffer brb = new BitReaderBuffer((ByteBuffer) bb.rewind());
        int sync = brb.readBits(11); // A
</pre>
and everything worked fine up to a >>> 4 on sync.   However, if I did a >>> 5, the bits would then get scrambled.  It is as if the jvm is improperly optimizing the code or messing up the memory alignment.

I've tested these things against multiple releases:
isoparser-1.0.3.11.jar	isoparser-1.0.4.1.jar	isoparser-1.0.4.2.jar

Any ideas?

**Comment by msrahmanian** [comment]
Hi
I had this challenge with MP3TrackImpl and finally found mp3agic java library that can remove mp3 tags from the original mp3 file and then the MP3TrackImpl can accept the mp3 file, now one issue is remained that when I append the MP3 file to the Mp4 video it can not be played in some players while the ACCTrackImpl does not have this problem, is there any suggesion for that ? I really appreciate any kind of help, the code and mp3agic library link is as following:

mp3agic : https://github.com/mpatric/mp3agic
Code:

                // removing mp3 tags
                Mp3File mp3file = new Mp3File(SDPathToFile("MyFilm", "a.mp3").getPath());
		if (mp3file.hasId3v1Tag()) {
		  mp3file.removeId3v1Tag();
		  Log.d("MP3agic","removeId3v1Tag");
		}
		if (mp3file.hasId3v2Tag()) {
		  mp3file.removeId3v2Tag();
		  Log.d("MP3agic","removeId3v2Tag");
		}
		if (mp3file.hasCustomTag()) {
		  mp3file.removeCustomTag();
		  Log.d("MP3agic","removeCustomTag");
		}
		mp3file.save(SDPathToFile("MyFilm", "a2.mp3").getPath());

               //appending mp3 to mp4 video
              Movie movie=new Movie();
	     movie=MovieCreator.build(new FileDataSourceImpl(SDPathToFile("MyFilm", "count-video.mp4")));
	     MP3TrackImpl audio=new MP3TrackImpl(new FileDataSourceImpl(SDPathToFile("MyFilm", "a2.mp3").getPath()));
	  
             CroppedTrack ct=new CroppedTrack(audio, 10, 500);
		 
	     movie.addTrack(ct);
	     Container mp4file = new DefaultMp4Builder().build(movie);
	     FileChannel fc = new FileOutputStream(SDPathToFile("MyFilm", "output2333aac.mp4")).getChannel();
	     mp4file.writeContainer(fc);
	     fc.close();

**Comment by gbildson** [comment]
Yeah, I ended up in a similar situation.  I'm not sure the support for mp3 music in mp4 is universal enough for my purposes. (i.e. web, iphone mobile web/app, android mobile web/app)

**Comment by msrahmanian** [comment]
Hi
Thanks for your replay, as the matter of fact I am developing an app which needs to append some MP3 files from the users device to the generated MP4, I would like to implement this without ffmpeg, I have tried so many libraries, and at the current time I am working on encoding mp3 files to aac with the help of JLayer for MP3 decoding and android-aac-enc ( https://github.com/timsu/android-aac-enc ) for aac endoing.
Sorry to ask, but do you have any solution for me ? or any alternative for that ?
Thank you so much

**Comment by sannies** [comment]
MP3 and MP4 just don't go together well. The name sounds similar but that's all. Use AAC if you can! MP3 was a good format but it is outdated

**Comment by sannies** [comment]
and please feel free to reopen if you need something done on the mp4parser.

**Comment by uditkumawat** [comment]
How to merge .mp3 and .mp4 files using any other library ? As MP4Parser does not support merging of .mp3 and .mp4 files.... MP3TrackImpl is not working correctly

**Comment by sannies** [comment]
Well, MP3TrackImpl is working but most players cannot playback MP3 tracks
in MP4 containers. Why wouldn't you convert your audio to AAC? There no
device on this planet that supports MP3 but not AAC.

How to merge .mp3 and .mp4 files using any other library ? As MP4Parser
does not support merging of .mp3 and .mp4 files.... MP3TrackImpl is not
working correctly

—
Reply to this email directly or view it on GitHub
<https://github.com/sannies/mp4parser/issues/25#issuecomment-107559137>.

**Comment by uditkumawat** [comment]
How can I add MP3TrackImpl.class or patch to the  isoviewer-1.0-27.jar ?
Please tell me full steps.

On Tue, Jun 2, 2015 at 12:31 AM, Sebastian Annies <notifications@github.com>
wrote:

> Well, MP3TrackImpl is working but most players cannot playback MP3 tracks
> in MP4 containers. Why wouldn't you convert your audio to AAC? There no
> device on this planet that supports MP3 but not AAC.
>
> How to merge .mp3 and .mp4 files using any other library ? As MP4Parser
> does not support merging of .mp3 and .mp4 files.... MP3TrackImpl is not
> working correctly
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sannies/mp4parser/issues/25#issuecomment-107559137>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sannies/mp4parser/issues/25#issuecomment-107672169>.
>



-- 
--
With Regards,
*Udit Kumawat*



*Final Year Student (B. Tech + M.Tech) Information TechnologyDepartment of
Integrated Post Graduation (IPG)Indian Institute of Information Technology
and Management, GwaliorMobile: +91-8989826236   *
*+91-9462100126 in.linkedin.com/in/uditkumawat94/
<http://in.linkedin.com/in/uditkumawat94/>*

**Comment by GirishBhutiya** [comment]
I can not use `Mp3File` in android. Is there any other way because I also faced same thing when merge 2 mp3 files which is recorded via android.
