### ISSUE TITLE
Mp4 Video Rotation doesnt work on windows media player | VLC

### ISSUE THREAD

**Issue by invincible1388** [sannies/mp4parser#27]
Hi 

First of all I want to thank for this wonderful plugin for video operations. I am facing issue in rotating the video . The rotation works fine on android player but when I try to upload it in my computer and play it then player (windows media player || VLC) doesnt consider the rotation and the video is played inverted.

Below is my code which does the rotation of the video:-

	        //rotate the video
	        Matrix deg;
	        if(rotation.equals("270")) //if stream recorded from front camera
	        	 deg = Matrix.ROTATE_270;
	        else 
	        	 deg = Matrix.ROTATE_90; //else stream is recorded from rear camera
	        
	        File input = new File(tempOutput);
            File output = new File(outFileName);

            IsoFile isoFile = new IsoFile(input.getAbsolutePath());
            Movie m = new Movie();
            List<TrackBox> trackBoxes = isoFile.getMovieBox().getBoxes(TrackBox.class);

            for (TrackBox trackBox : trackBoxes) {
                trackBox.getTrackHeaderBox().setMatrix(deg);
                m.addTrack(new Mp4TrackImpl("output1", trackBox) {
				});
            }

            Container finalContainer = new DefaultMp4Builder().build(m);
            @SuppressWarnings("resource")
			FileChannel finalStream = new RandomAccessFile(output.getAbsolutePath(), "rw").getChannel();
            finalContainer.writeContainer(finalStream);
            finalStream.close();
            isoFile.close();

This code works for android video player but doesnt support players like VLC or windows media player.

Am I missing something in the above code so that the video remains uniform in all the players.

Tks in advance.
Vilash

**Comment by sannies** [comment]
Sorry that I never came back to you. Some MP4 features are only supported by some players. That's the world we are living in.
