### ISSUE TITLE
how can i mix a wav and a mp4 ? 

### ISSUE THREAD

**Issue by hectoritoh** [sannies/mp4parser#31]

**Comment by sannies** [comment]
There is no specification that tells us how to embed wav samples in an MP4 container therefore this will not work. Something that might be close to wav in MP4 is MP4 audio lossless coding (http://en.wikipedia.org/wiki/Audio_Lossless_Coding) as specified in ISO/IEC 14496-3. This is - as far as I know - a well and widely supported way to have lossless audio in MP4. 
I'm not sure why you ask for this: Is it case you want to store the audio lossless or cause the PCM is the only data you have and you don't want to use an encoder?

**Comment by sannies** [comment]
Closing this ticket. Please open new ticket in case you want ALS support.
