### ISSUE TITLE
Generate lots of huge size tmp MediaDataBox files after cutting and appending MP4 clips 

### ISSUE THREAD

**Issue by evanQD** [sannies/mp4parser#315]
Hi,

I found lots of huge size tmp files after cutting and appending MP4 clips:
Any solution I can apply?

isoparser and muxer version is 1.9.34.

[root@localhost temp]# du -h *
11M     MediaDataBox3353323537304459708org.mp4parser.boxes.iso14496.part12.MediaDataBox@648dabab
38M     MediaDataBox4936790949145394189org.mp4parser.boxes.iso14496.part12.MediaDataBox@2d9239fc
5.8M    MediaDataBox533456596869457275org.mp4parser.boxes.iso14496.part12.MediaDataBox@334394a1
3.1G    MediaDataBox8634033729187507380org.mp4parser.boxes.iso14496.part12.MediaDataBox@2f5cd9a4

Thanks 
Evan

**Comment by avanibhatnagar** [comment]
Hey sorry this is another question and not an answer.. I added the muxer dependency in pom.xml, but it still says can't resolve 'muxer', and I get the following errors:

![image](https://user-images.githubusercontent.com/25621222/42702815-75e55f96-867f-11e8-9284-c378b61cfe78.png)

I was hoping you could help me?

**Comment by lonely-lockley** [comment]
Met this problem too. It seems you do not call close() on IsoFile instances you create. I've run out of /tmp space when just wanted to list and display video and audio streams metadata.
Is it really necessary to unpack the full media into /tmp when i'm just reading content?

**Comment by thomasburguiere** [comment]
Hello

Thanks a lot for this fix, but I think it will not solve the issue on server-side applications. Since the process never exists, the files will not be deleted, and that leads to running out of disk space.

I think `mp4parser` should provide a way to frees up resources such as disk space.

Would there be a way to ensure that  `MediaDataBox` (or `ParseableBox` /  `Box`) implements `Closeable` ??

best regards

**Comment by neorevx** [comment]
I have same problem. Any one know where I can access MediaDataBox to change source files and delete tmp file?

**Comment by scooter1556** [comment]
I am using this library as part of a server-side media transcoding solution and have realised today that my /tmp directory is consuming 150GB and contains hundreds of MediaDataBox* files. The application isn't designed to be restarted frequently and can run for weeks/months/years which makes this a big issue. Is there an alternative way to ensure temp files get cleaned up on closing of an IsoFile? The only other thing I can think to do is add a routine to frequently check for temp files and delete them but this isn't ideal and seems hacky.
