### ISSUE TITLE
Can't resolve muxer

### ISSUE THREAD

**Issue by avanibhatnagar** [sannies/mp4parser#316]
I added the maven dependency for muxer:
<dependency>
	<groupId>org.mp4parser</groupId>
        <artifactId>muxer</artifactId>
	<version>1.9.27</version>
</dependency>

But it still shows that it can't resolve symbol 'muxer'

**Comment by mslinn** [comment]
Here is the Maven release information:

    https://mvnrepository.com/artifact/org.mp4parser/muxer
