### ISSUE TITLE
H264TrackImpl AACTrackImpl  create mp4 can not play in VLC

### ISSUE THREAD

**Issue by shoyu666** [sannies/mp4parser#319]
dear author
use H264TrackImpl and AACTrackImpl  create mp4

final 1532667754113A2.mp4 can not play int 'vlc'  why?
        but can play in 'windows media player'

` 
public class Mux {
    public static void main(String[] args) throws IOException, XPathExpressionException, SAXException, ParserConfigurationException, URISyntaxException {
        String fileName = "C:\\Users\\n\\Desktop\\h264\\test\\1532667754113";
    	Movie v = new Movie();
        Track audio = new H264TrackImpl(new FileDataSourceImpl(fileName+".h264"));
        v.addTrack(audio);
        AACTrackImpl aacTrack = new AACTrackImpl(new FileDataSourceImpl(fileName+".aac"));
        v.addTrack(aacTrack);
        Mp4Builder defaultMp4Builder = new DefaultMp4Builder();
        Container c = defaultMp4Builder.build(v);
        File out = new File(fileName+"A2.mp4");
        c.writeContainer(new FileOutputStream(out).getChannel());
    }
}

`

[test.zip](https://github.com/sannies/mp4parser/files/2234731/test.zip)

**Comment by sannies** [comment]
Hmm, not sure what the problem might be here. Would you please verify that
C:\Users\n\Desktop\h264\test\1532667754113 plays in VLC?
C:\Users\n\Desktop\h264\test\1532667754113 should be an Annex B bitstream.
What kind of file is C:\Users\n\Desktop\h264\test\1532667754113?

2018-07-27 8:36 GMT+02:00 shoyu666 <notifications@github.com>:

**Comment by shoyu666** [comment]
@sannies 
thinks for you reply  (I am sorry for my poor english)
i has upload a zip 
1532667754113 .aac
1532667754113 .h264

i try create mp4 (1532667754113 .aac+1532667754113 .h264)
i try create mp4 (1532667754113 .h264)
can not play in vlc(https://www.videolan.org/)
can not play in mac 
need you help

**Comment by sannies** [comment]
Please make the h264 file available to me.

**Comment by shoyu666** [comment]
dear author 
--Please make the h264 file available to me.
   do you mean h264 soure file? 
    can you see zip file i have upload ?

**Comment by shoyu666** [comment]
@sannies 
i get raw h264 file by  android MediaCodec
in front  i  wirte 
write outputFormat.getByteBuffer("csd-0")
write outputFormat.getByteBuffer("csd-1")

write MediaCodec   OutputBuffer data;

write MediaCodec OutputBuffer data;
..................
write MediaCodec OutputBuffer data;

**Comment by sannies** [comment]
got it, sorry. didn't see the zip

**Comment by shoyu666** [comment]
@sannies 
thanks, ; possible causes i am in china

i upload to github
https://github.com/shoyu666/Hand-Signature/blob/master/files.zip
can you down load ?

**Comment by sannies** [comment]
The H264TrackImpl didn't correctly parse the Sample objects from the file as it didn't set the SampleDescription thus it could set the sample derscription index correctly when writing the MP4. 
I published 1.9.36 with that fix.
