### ISSUE TITLE
Muxing mp4 DASH tracks

### ISSUE THREAD

**Issue by kapodamy** [sannies/mp4parser#324]
I'm trying to mux two tracks from two different files (`m4v` and `m4a` files respectively) both files are DASH type. The generated `MP4` file is not created correctly. Also, Windows Explorer does not show a thumbnail

The code I use:
```java
public static Track loadTrackFrom(String path) {
  Movie m4 = MovieCreator.build(path);
  return m4.getTracks().get(0);
}

public static void Main(String[] args) {
    Track m4v = loadTrackFrom("video-dash.m4v");
    Track m4a = loadTrackFrom("audio-dash.m4a");
    RandomAccessFile raf = new RandomAccessFile("merged.mp4", "rw");
    
    Movie m = new Movie();
    m.addTrack(m4v);
    m.addTrack(m4a);

    DefaultMp4Builder builder = new DefaultMp4Builder();
    Container stdMp4 = builder.build(m);
    stdMp4.writeContainer(raf.getChannel());
    raf.close();
}
```

In the merged file the following fields are empty:
1. moov/trak[0]/edts/elst{0}.segmentDuration
2. moov/trak[0]/mdia/hdlr.name (is optional?)
3. moov/trak[1]/mdia/hdlr.name (is optional?)

**Comment by sannies** [comment]
Hi,
would you be able to create a PR for hdlr name and segment duration (how can segment duration be empty? Isn't it a 32 bit integer? It can be empty but missing?)
The additional 8 bytes don't do any harm (besides wasting 8 bytes). By always adding 8 bytes I have enough room for the extended size field when mdat becomes larger than 2GB and thereby the offset calculation is simplified.

**Comment by kapodamy** [comment]
> Isn't it a 32 bit integer? It can be empty but missing?

I mean values are 0 and about `mdat`, i did not know that.

**Comment by sannies** [comment]
The value that is zero describes a time-shift of the track in the movie
timeline. It would surprise me if zero were a problem as zero is a very
typical value.

kapodamy <notifications@github.com> schrieb am So., 5. Aug. 2018, 17:38:

**Comment by kapodamy** [comment]
Ok, `moov/trak[0]/edts/elst{0}.segmentDuration` it doesnt need to have a non-zero value.
using Icaros ThumbnailProvider (included with K-Lite Codec Pack) can be zero but with default Windows explorer thumbnail provider no. Its strange.

also researching better the file `moov/trak[0]/tkhd.duration` is **zero**.

in conclusion, to obtain a thumbnail with any thumbnail provider setting... :
`moov/mvhd.timeScale` to `1000`.
`moov/mvhd.duration` to `duration / timeScale * 1000`
`moov/trak[0]/tkhd.duration`  with the same value in `moov/trak[0]/mdia/mdhd.duration`
`moov/trak[0]/edts/elst{0}.segmentDuration` with the track duration in miliseconds.

track[0] is the video track
