### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError (AbstractBox.java)

### ISSUE THREAD

**Issue by HBiSoft** [sannies/mp4parser#342]
I'm using a older version, back when the package was still `com.google.mp4parser` and recently I started getting ANR's on devices running 7.0. It points to line 110 in `AbstractBox.java`:

```
this.content = ByteBuffer.allocate(CastUtils.l2i(contentSize));
```

and the ANR happens when calling:

```
MediaInfo mediaInfo = new MediaInfo();
```

I had a look at all the issues and I found this one (#139).

Is it save to say that the latest release fixed this issue because @sannies approved this pull request on the 3rd of Aug - (https://github.com/sannies/mp4parser/pull/288)

Also, I noticed that the `isoparser` and `muxer` is now spilt into 2 "projects" - Am I correct in downloading `isopaser` and `muxer` jar files separately and adding them as separate jars into my project?

**Comment by HBiSoft** [comment]
Fixed in latest release

**Comment by rajeevrocker7** [comment]
@HBiSoft Hi, can you please tell me release version in which [https://github.com/sannies/mp4parser/issues/139](url)
is resolved. ??
