### ISSUE TITLE
Track Header box duration does not account for edits 

### ISSUE THREAD

**Issue by michschn** [sannies/mp4parser#41]
According to the duration documentation of the tkhd box, "[...] the value of this field is equal to the sum of the durations of all of the track’s edits. If there is no edit list, then the duration is the sum of the sample durations [...]"

Yet, DefaultMp4Builder delegates to Track#getDuration() for both, the tkhd and mdhd, always returning the total sample duration, thus not allowing edits to create a track that is shorter than the media.

**Comment by sannies** [comment]
Good find. Thx

**Comment by sannies** [comment]
I think i fixed it. Please have a look and see if it solves your problem
