### ISSUE TITLE
null pointer exception

### ISSUE THREAD

**Issue by mohanraj546** [sannies/mp4parser#46]
hai sannies,

I am getting null pointer exception at

at com.googlecode.mp4parser.authoring.tracks.H264TrackImpl$SliceHeader.<init>(H264TrackImpl.java:541)

for the below code,

H264TrackImpl h264Track = new H264TrackImpl(new FileDataSourceImpl(android.os.Environment.getExternalStorageDirectory().getAbsolutePath() + "/test.h264"));

 Movie movie = new Movie();
movie.addTrack(h264Track);
Container mp4file = new DefaultMp4Builder().build(movie);

FileChannel fc = new FileOutputStream(new File(android.os.Environment.getExternalStorageDirectory().getAbsolutePath() + "/decodingvideo.mp4")).getChannel();
 mp4file.writeContainer(fc);
 fc.close();

Please help me how to do this?

**Comment by sannies** [comment]
Hi,
from the line number I can see that you are not using the latest version. Would you please check the latest version and attach an example file. I've often seen that those errors are only reproducable with very specific input material.
Beste Grüße,
Sebastian

**Comment by mohanraj546** [comment]
hai sannies,

i send the java file and test.h264 file.Please check that one..

**Comment by mohanraj546** [comment]
hai sannies,

did u check it?give me reply please...

**Comment by sannies** [comment]
I didn't find the file anywhere and got distracted.  Where did you send me
the file again?
Am 03.02.2015 06:17 schrieb "mohanraj546" <notifications@github.com>:

**Comment by mohanraj546** [comment]
please check this one

**Comment by mohanraj546** [comment]
hai sannies
 did u checked or not?

**Comment by mohanraj546** [comment]
hai sannies,
did u checked?

**Comment by sannies** [comment]
Hi Mohan (I guess that's your name),

please keep in mind that all I do here is done in my spare time. I assume you get money for what you are doing here so please don't push too hard and try to be polite in your emails - that means say "Hello/Hi [receipient's name]" in the beginning and "Best Regards/Regards/your local flavor of it and [your name]" in the end. 
A hint: When someone states his name at the end of an email this is usually the name you should use to address him next time. 
Thanks for listening. 

Now to the real problem:
Where is the damn example file? How did you send it to me? I didn't find anything in my emails. Now would have been the time where I had some time to work on it but unfortunately I cannot start without the example. 
You have also not confirmed that you are using the latest version. 
I looks like that you cannot attach files here, right? So please upload it somewhere and post the link here. Reopen the issue whenever you think I should have access to the file. 

Best Regards,
Sebastian

**Comment by mohanraj546** [comment]
sorry for what i had done

**Comment by sannies** [comment]
Don't mind. I was annoyed yesterday. Today is a new day. Just make the h264
available and I'll take a look!
Am 09.02.2015 06:21 schrieb "mohanraj546" <notifications@github.com>:

**Comment by mohanraj546** [comment]
okay thank u so much.
