### ISSUE TITLE
can you give me an example for trimming mp4 video file?

### ISSUE THREAD

**Issue by samirae** [sannies/mp4parser#53]
i was trying to trim (cut) a mp4 video file, and i failed:). is there any examples available for me?
thanks a lot

**Comment by samirae** [comment]
try {
			H264TrackImpl h264Track = new H264TrackImpl(new FileDataSourceImpl(
					moviePath));
			Movie movie = new Movie();
			movie.addTrack(h264Track);

			Container mp4file = new DefaultMp4Builder().build(movie);

			FileChannel fc = new FileOutputStream(new File(outputPath))
					.getChannel();
			mp4file.writeContainer(fc);
			fc.close();

		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		} catch (Exception e) {
			e.printStackTrace();
		}



thats my code and this is error:

03-03 11:44:46.293: E/AndroidRuntime(5929): FATAL EXCEPTION: main
03-03 11:44:46.293: E/AndroidRuntime(5929): java.lang.ExceptionInInitializerError
03-03 11:44:46.293: E/AndroidRuntime(5929): 	at com.googlecode.mp4parser.authoring.tracks.H264TrackImpl.parse(H264TrackImpl.java:127)
03-03 11:44:46.293: E/AndroidRuntime(5929): 	at com.googlecode.mp4parser.authoring.tracks.H264TrackImpl.<init>(H264TrackImpl.java:90)
03-03 11:44:46.293: E/AndroidRuntime(5929): 	at com.googlecode.mp4parser.authoring.tracks.H264TrackImpl.<init>(H264TrackImpl.java:96)
03-03 11:44:46.293: E/AndroidRuntime(5929): 	at com.googlecode.mp4parser.authoring.tracks.H264TrackImpl.<init>(H264TrackImpl.java:100)
03-03 11:44:46.293: E/AndroidRuntime(5929): 	at com.example.isoparser.MainActivity.onCreate(MainActivity.java:32)
03-03 11:44:46.293: E/AndroidRuntime(5929): 	at android.app.Activity.performCreate(Activity.java:4531)
03-03 11:44:46.293: E/AndroidRuntime(5929): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1071)
03-03 11:44:46.293: E/AndroidRuntime(5929): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2150)
03-03 11:44:46.293: E/AndroidRuntime(5929): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2229)
03-03 11:44:46.293: E/AndroidRuntime(5929): 	at android.app.ActivityThread.access$600(ActivityThread.java:139)
03-03 11:44:46.293: E/AndroidRuntime(5929): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1261)
03-03 11:44:46.293: E/AndroidRuntime(5929): 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-03 11:44:46.293: E/AndroidRuntime(5929): 	at android.os.Looper.loop(Looper.java:154)
03-03 11:44:46.293: E/AndroidRuntime(5929): 	at android.app.ActivityThread.main(ActivityThread.java:4945)
03-03 11:44:46.293: E/AndroidRuntime(5929): 	at java.lang.reflect.Method.invokeNative(Native Method)
03-03 11:44:46.293: E/AndroidRuntime(5929): 	at java.lang.reflect.Method.invoke(Method.java:511)
03-03 11:44:46.293: E/AndroidRuntime(5929): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
03-03 11:44:46.293: E/AndroidRuntime(5929): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
03-03 11:44:46.293: E/AndroidRuntime(5929): 	at dalvik.system.NativeStart.main(Native Method)
03-03 11:44:46.293: E/AndroidRuntime(5929): Caused by: java.lang.NoClassDefFoundError: org.aspectj.runtime.reflect.Factory
03-03 11:44:46.293: E/AndroidRuntime(5929): 	at com.mp4parser.iso14496.part15.AvcConfigurationBox.ajc$preClinit(AvcConfigurationBox.java:1)
03-03 11:44:46.293: E/AndroidRuntime(5929): 	at com.mp4parser.iso14496.part15.AvcConfigurationBox.<clinit>(AvcConfigurationBox.java:1)
03-03 11:44:46.293: E/AndroidRuntime(5929): 	... 19 more

**Comment by sannies** [comment]
I can see that you are not using the latest version. please use latest
version or at least tell me which one you are using.
Am 03.03.2015 09:16 schrieb "Samira" <notifications@github.com>:

**Comment by samirae** [comment]
Problem solved:)

**Comment by samirae** [comment]
thanks dude

**Comment by tomorrowbetter** [comment]
Another way is to use iDealshare VideoGo to trim MP4 files on Mac or Windows 

Step by step guide at http://www.idealshare.net/trim-video-mp4-mkv-avi-mov-wmv.html

    Work as an easy-to-use MP4 Trimmer, iDealshare VideoGo  can  cut MP4 files as well as keep the source format or convert MP4 to  numerous popular video formats like AVI, MOV, WMV, FLV, ASF, MPEG, MXF,  WebM, DV, RM, etc;
    Besides as an MP4 Cutter, iDealshare VideoGo  can cut various  kinds of video and movie such as cut AVI, cut MOV, cut WMV, cut MKV,  WTV, FLV, OGV, 3GP, AVCHD, MTS, ASF, SWF, MXF, WebM, MOD, DV, RM, TS,  XMV;
    iDealshare VideoGo works as more than a Video Cutter. It  also supports cutting nearly all kinds of audio files like cut MP3, WAV,  AAC, AC3, M4A, ALAC, FLAC, AIFF, CAF, M4B, APE, OPUS, WMA, AU, DTS,  MP2, GSM, VOC and more;
    Cut video and audio in the meanwhile with or without re-encoding;
    More editing functions: crop, merge files, split by chapter,  add effect/watermark/subtitle to video, adjust volume/bitrate/frame rate  of video, rotate video in 90 Degrees/180 Degrees/270 Degrees, change  video aspect ratio, compress video and audio, remove or extract audio  from video, extract subtitle from video and more;
    Compatible with both Mac (OS X Yosemite included) and Windows (windows 8 included).

**Comment by aimkeepachieve** [comment]
I just find an easy method to trim mp4 video file.
Here is the step by step gudie at http://www.idealshare.net/trim-video-mp4-mkv-avi-mov-wmv.html

**Comment by samirae** [comment]
Thank u

Samira Ekrami

**Comment by sannies** [comment]
Hi,
I'm closing the issue. It's no longer an mp4parser thing. Glad that you found something that works for you.
Sebastian

**Comment by samirae** [comment]
thank you for all your work so far.


On Tue, Jun 23, 2015 at 9:43 AM, Sebastian Annies <notifications@github.com>
wrote:

> Hi,
> I'm closing the issue. It's no longer an mp4parser thing. Glad that you
> found something that works for you.
> Sebastian
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sannies/mp4parser/issues/53#issuecomment-114361523>.
>



-- 
                  Regards
                  Samira Ekrami

**Comment by sriramtej** [comment]
can you give me the code of video parsing i am facing issues with my code

**Comment by sriramtej** [comment]
i want to give starting and ending seconds value of video which needs  to be trimmed and creating movie object using file path

**Comment by sannies** [comment]
Would you please describe what kind of problems you are facing?
To be honest; your question sounds a bit like <I don't want to think.
Could someone else please do it? >

sriramtej <notifications@github.com> schrieb am Fr., 13. Nov. 2015 8:18 PM:

**Comment by sriramtej** [comment]
Absolutely yes at that point of time but i finished it anyhow .
