### ISSUE TITLE
Mux two acc to a mp4.

### ISSUE THREAD

**Issue by chenweitracy** [sannies/mp4parser#55]
Hi,Sannies
    This is the issus.I 'm trying to mux two acc to a mp4,but the generated mp4 only play m2.acc.
    Please help me,thx.
        
        String video1 = "F:/media/v1.mp4";
        String track1 = "F:/media/m1.aac";
        String track2 = "F:/media/m2.aac";

        Movie m = MovieCreator.build(video1);
        
        AACTrackImpl aac1 = new AACTrackImpl(new FileDataSourceImpl(track1));
        AACTrackImpl aac2 = new AACTrackImpl(new FileDataSourceImpl(track2));
        
        m.addTrack(aac1);
        m.addTrack(aac2);
        
        DefaultMp4Builder mp4Builder = new DefaultMp4Builder();
        Container out = mp4Builder.build(m);
        FileOutputStream fos = new FileOutputStream("output.mp4");
        FileChannel fc = fos.getChannel();
        out.writeContainer(fc);
        fos.close();

**Comment by chenweitracy** [comment]
Is that m2.acc replaced m1.acc?

**Comment by sannies** [comment]
No.
Am 04.03.2015 12:02 schrieb "chenweitracy" <notifications@github.com>:

**Comment by chenweitracy** [comment]
Now i found an issue.First I mux a video with an audio,then I try to mux the generated mp4 with another audio,it's useless,why?
Could you tell me,thx.

**Comment by hierophantzw** [comment]
did u solve this issue?when  I muxing the acc file into mp4,a runtime exception happenen ,it says no box object founded for ftyp
