### ISSUE TITLE
no box object found fot fytp

### ISSUE THREAD

**Issue by hierophantzw** [sannies/mp4parser#56]
hi,sannies,when I muxing an acc file(8seconds) into a mp4 file,a runtime exception (no box object found for fytp)happened ,can u help me ?waitting for your replay...

**Comment by hierophantzw** [comment]
ftyp,not fytp,sorry.

**Comment by hierophantzw** [comment]
by the way ,I am a android developer,and I use the   mp4parser lib  for developing .

**Comment by heirophantzw** [comment]
sannies,sorry to trouble you ,since I have updated the libraries,the issue has been solved perfectly ,thanks.you r a genius,and so am I...haha
