### ISSUE TITLE
Cutting/Shorten Videos not extractly

### ISSUE THREAD

**Issue by kyniema4** [sannies/mp4parser#57]
I have try to cut a part of a video. The input video's time is 10 minutes.
startTime = 60
endTime = 300
=>The generated output's time must be 4 minutes length.
The output is generated but not extractly. Output video's time is 2 minutes.
Can you give me an method to fix it?

**Comment by kyniema4** [comment]
Here is my source code:

public static void trimVideo(final String srcFileDir , final String outFileDir ,final double fromSecond , final double toSecond ) 
			throws IOException {
		
		if(fromSecond < 0){
			return;
		}
		
		Movie movie = MovieCreator.build( new FileDataSourceImpl(srcFileDir));
		
		List<Track> tracks = movie.getTracks();
		Log.e("tracks size" , "track size ="+ tracks.size());
        movie.setTracks(new LinkedList<Track>());
        
        double startTime = 0 , endTime = 0;
        
        
        boolean timeCorrected = false;
        
        // Here we try to find a track that has sync samples. Since we can only start decoding
        // at such a sample we SHOULD make sure that the start of the new fragment is exactly
        // such a frame
        for (Track track : tracks) {
            if (track.getSyncSamples() != null && track.getSyncSamples().length > 0) {
                if (timeCorrected) {
                    // This exception here could be a false positive in case we have multiple tracks
                    // with sync samples at exactly the same positions. E.g. a single movie containing
                    // multiple qualities of the same video (Microsoft Smooth Streaming file)

                    throw new RuntimeException("The startTime has already been corrected by another track with SyncSample. Not Supported.");
                }
                startTime = correctTimeToNextSyncSample(track, fromSecond);
                endTime = correctTimeToNextSyncSample(track, toSecond);
                timeCorrected = true;
            }
        }
        Log.e("track list "," start time="+ startTime + " end Time ="+ endTime);
        for (Track track : tracks) {
            long currentSample = 0;
            double currentTime = 0;
            long startSample = -1;
            long endSample = -1;
            Log.e("TRACKLIST","size track =" +track.getDecodingTimeEntries().size());
            for (int i = 0; i < track.getDecodingTimeEntries().size(); i++) {
                TimeToSampleBox.Entry entry = track.getDecodingTimeEntries().get(i);
                //Log.e("TRACKLIST", "entry count =" + entry.getCount());
                for (int j = 0; j < entry.getCount(); j++) {
                    // entry.getDelta() is the amount of time the current sample covers.
                	
                    if (currentTime <= startTime) {
                        // current sample is still before the new starttime
                        startSample = currentSample;
                    }
                    if (currentTime <= endTime) {
                        // current sample is after the new start time and still before the new endtime
                        endSample = currentSample;
                    } else {
                        // current sample is after the end of the cropped video
                    	if(endSample == -1){
                    		endSample = currentSample;
                    	}
                        break;
                    }
                    currentTime += (double) entry.getDelta() / (double) track.getTrackMetaData().getTimescale();
                    currentSample++;
                }
            }
            Log.e("TRACKLIST2","startSample ="+startSample + " endSample="+endSample);
            movie.addTrack(new CroppedTrack(track, startSample, endSample));
        }
        
        Container container = new DefaultMp4Builder().build(movie);
        
        final FileOutputStream fos = new FileOutputStream(new File(String.format(outFileDir)));
	    final WritableByteChannel bb = Channels.newChannel(fos);
	    container.writeContainer(bb);
	    fos.close();
        
	}
private static double correctTimeToNextSyncSample(Track track, double cutHere) {
        double[] timeOfSyncSamples = new double[track.getSyncSamples().length];
        long currentSample = 0;
        double currentTime = 0;
        for (TimeToSampleBox.Entry entry : track.getDecodingTimeEntries()) {
            for (int j = 0; j < entry.getCount(); j++) {
                if (Arrays.binarySearch(track.getSyncSamples(), currentSample + 1) >= 0) {
                    // samples always start with 1 but we start with zero therefore +1
                    timeOfSyncSamples[Arrays.binarySearch(track.getSyncSamples(), currentSample + 1)] = currentTime;
                }
                Log.e("","");
                currentTime += (double) entry.getDelta() / (double) track.getTrackMetaData().getTimescale();
                currentSample++;
            }
        }
        for (double timeOfSyncSample : timeOfSyncSamples) {
            if (timeOfSyncSample > cutHere) {
                return timeOfSyncSample;
            }
        }
        return timeOfSyncSamples[timeOfSyncSamples.length - 1];
    }

**Comment by kyniema4** [comment]
somebody help me please

**Comment by sannies** [comment]
Please provide the video file as it might have something to do with it.

2015-03-16 4:58 GMT+02:00 kyniema4 <notifications@github.com>:

**Comment by kyniema4** [comment]
https://www.dropbox.com/s/5d11vqtxeom6gmw/ffff.mp4?dl=0

that is my input video. 
regards.

**Comment by sannies** [comment]
Unfortunately you are using an old version of the library. I will not support that version in any way. 

I ported your code to the latest isoparser version. It crashes at the moment as the input video is a bit uncommon: The sample to chunk box announces chunks that don't contain samples. I'm not sure if that is valid at all but as I can handle it with minor modifications I won't make the parser reject the file.

Nevertheless I'll need a bit more time. Let's see perhaps I'll repair it on the weekend or Monday.

**Comment by sannies** [comment]
Ok, I fixed the issue with zero samples in a chunk. 
https://github.com/sannies/mp4parser/commit/1e163072e13bf4d46de654ec40301dd4fdbad7a0
(btw - this is commit no. 1000!!!)

Unfortunately the way the video is encoded prohibits precise cutting of the video. The sample are of variable duration. The longest samples is displayed ~3.5 seconds and at the same time IDR samples are only inserted ~500 frames. 

The isoparser can only cut the video at those frames as it cannot re-encode. Therefor the start and end times are adjusted to the next IDR frame which is in your case very far away.

Here the code working with the latest isoparser version:


package com;
    
    import com.coremedia.iso.boxes.Container;
    import com.googlecode.mp4parser.FileDataSourceImpl;
    import com.googlecode.mp4parser.authoring.Movie;
    import com.googlecode.mp4parser.authoring.Track;
    import com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder;
    import com.googlecode.mp4parser.authoring.container.mp4.MovieCreator;
    import com.googlecode.mp4parser.authoring.tracks.CroppedTrack;
    
    import java.io.File;
    import java.io.FileOutputStream;
    import java.io.IOException;
    import java.nio.channels.Channels;
    import java.nio.channels.WritableByteChannel;
    import java.util.Arrays;
    import java.util.LinkedList;
    import java.util.List;
    
    
    /**
     * Created by sannies on 19.03.2015.
     */
    public class ShortenCheck {
        static class Log {
    
            public static void e(String s, String s1) {
            //    System.err.println(s + " -- " + s1);
            }
        }
    
    
    
        public static void main(String[] args) throws IOException {
            trimVideo("C:\\Users\\sannies\\Downloads\\ffff.mp4", "c:\\dev\\cut.mp4", 60, 300);
        }
    
        public static void trimVideo(final String srcFileDir, final String outFileDir, final double fromSecond, final double toSecond)
                throws IOException {
    
            if (fromSecond < 0) {
                return;
            }
    
            Movie movie = MovieCreator.build(new FileDataSourceImpl(srcFileDir));
    
            List<Track> tracks = movie.getTracks();
            Log.e("tracks size", "track size =" + tracks.size());
            movie.setTracks(new LinkedList<Track>());
    
            double startTime = 0, endTime = 0;
    
    
            boolean timeCorrected = false;
    
            // Here we try to find a track that has sync samples. Since we can only start decoding
            // at such a sample we SHOULD make sure that the start of the new fragment is exactly
            // such a frame
            for (Track track : tracks) {
                if (track.getSyncSamples() != null && track.getSyncSamples().length > 0) {
                    if (timeCorrected) {
                        // This exception here could be a false positive in case we have multiple tracks
                        // with sync samples at exactly the same positions. E.g. a single movie containing
                        // multiple qualities of the same video (Microsoft Smooth Streaming file)
    
                        throw new RuntimeException("The startTime has already been corrected by another track with SyncSample. Not Supported.");
                    }
                    startTime = correctTimeToNextSyncSample(track, fromSecond);
                    System.err.println("corrected starttime from " + fromSecond + " to " + startTime);
                    endTime = correctTimeToNextSyncSample(track, toSecond);
                    System.err.println( "corrected endTime from " + toSecond + " to " + endTime);
                    timeCorrected = true;
                }
            }
            Log.e("track list ", " start time=" + startTime + " end Time =" + endTime);
            for (Track track : tracks) {
                long currentSample = 0;
                double currentTime = 0;
                long startSample = -1;
                long endSample = -1;
                Log.e("TRACKLIST", "size track =" + track.getSampleDurations().length);
                for (int i = 0; i < track.getSampleDurations().length; i++) {
                    long delta = track.getSampleDurations()[i];
                    //Log.e("TRACKLIST", "entry count =" + entry.getCount());
                    for (int j = 0; j < 1; j++) {
                        // entry.getDelta() is the amount of time the current sample covers.
    
                        if (currentTime <= startTime) {
                            // current sample is still before the new starttime
                            startSample = currentSample;
                        }
                        if (currentTime <= endTime) {
                            // current sample is after the new start time and still before the new endtime
                            endSample = currentSample;
                        } else {
                            // current sample is after the end of the cropped video
                            if (endSample == -1) {
                                endSample = currentSample;
                            }
                            break;
                        }
                        currentTime += (double) delta / (double) track.getTrackMetaData().getTimescale();
                        currentSample++;
                    }
                }
                Log.e("TRACKLIST2", "startSample =" + startSample + " endSample=" + endSample);
                movie.addTrack(new CroppedTrack(track, startSample, endSample));
            }
            Container container = new DefaultMp4Builder().build(movie);
            final FileOutputStream fos = new FileOutputStream(new File(String.format(outFileDir)));
            final WritableByteChannel bb = Channels.newChannel(fos);
            container.writeContainer(bb);
            fos.close();
    
        }
    
        private static double correctTimeToNextSyncSample(Track track, double cutHere) {
            double[] timeOfSyncSamples = new double[track.getSyncSamples().length];
            long currentSample = 0;
            double currentTime = 0;
            for (long dur : track.getSampleDurations()) {
                for (int j = 0; j < 1; j++) {
                    if (Arrays.binarySearch(track.getSyncSamples(), currentSample + 1) >= 0) {
                        // samples always start with 1 but we start with zero therefore +1
                        timeOfSyncSamples[Arrays.binarySearch(track.getSyncSamples(), currentSample + 1)] = currentTime;
                    }
                    Log.e("", "");
                    currentTime += (double) dur / (double) track.getTrackMetaData().getTimescale();
                    currentSample++;
                }
            }
            for (double timeOfSyncSample : timeOfSyncSamples) {
                if (timeOfSyncSample > cutHere) {
                    return timeOfSyncSample;
                }
            }
            return timeOfSyncSamples[timeOfSyncSamples.length - 1];
        }
    
    }

**Comment by sannies** [comment]
unresolvable
