### ISSUE TITLE
MovieCreator.build(String) throwing NPE

### ISSUE THREAD

**Issue by gitanuj** [sannies/mp4parser#58]
I'm trying to append 2 mp4 audio tracks. Looks like IsoFile.getMovieBox() returns null at MovieCreator.java:51.

I'm using standard files generated by akamai for HLS streaming. Here's the link to one of the files https://dl.dropboxusercontent.com/u/1149078/segment1.mp4

**Comment by sannies** [comment]
It looks like you do compile the software on your own and don't correctly perform the aspectJ compile time weaving.
