### ISSUE TITLE
Is it possible with mp4parser to read h.264's profile and it's level from an mp4 file?

### ISSUE THREAD

**Issue by igormukhin** [sannies/mp4parser#62]
Is it possible with mp4parser to read h.264's profile and it's level from an mp4 file? Can you provide an example?
Thank you.

**Comment by sannies** [comment]
Navigate to the avcC box.
Info is there.

Sent from phone, Sebastian
Am 26.03.2015 17:53 schrieb "Igor Mukhin" <notifications@github.com>:
