### ISSUE TITLE
Estimating size of Shortened Video

### ISSUE THREAD

**Issue by renatofernandes28** [sannies/mp4parser#68]
Is there a quick non-expensive way to find the size of a trimmed video without actually writting to a file yet
.. here is the shorted example code

            Movie movie = MovieCreator.build(_videoPath);

            List<Track> tracks = movie.getTracks();
            movie.setTracks(new LinkedList<Track>());
            // remove all tracks we will create new tracks from the old

            double startTime1 = (double) start;
            double endTime1 = (double) end;

            boolean timeCorrected = false;

            // Here we try to find a track that has sync samples. Since we can only start decoding
            // at such a sample we SHOULD make sure that the start of the new fragment is exactly
            // such a frame
            for (Track track : tracks) {
                if (track.getSyncSamples() != null && track.getSyncSamples().length > 0) {
                    if (timeCorrected) {
                        // This exception here could be a false positive in case we have multiple tracks
                        // with sync samples at exactly the same positions. E.g. a single movie containing
                        // multiple qualities of the same video (Microsoft Smooth Streaming file)

                        throw new RuntimeException("The startTime has already been corrected by another track with SyncSample. Not Supported.");
                    }
                    startTime1 = correctTimeToSyncSample(track, startTime1, false);
                    endTime1 = correctTimeToSyncSample(track, endTime1, true);
                    timeCorrected = true;
                }
            }

            for (Track track : tracks) {
                long currentSample = 0;
                double currentTime = 0;
                double lastTime = -1;
                long startSample1 = -1;
                long endSample1 = -1;

                for (int i = 0; i < track.getSampleDurations().length; i++) {
                    long delta = track.getSampleDurations()[i];

                    if (currentTime > lastTime && currentTime <= startTime1) {
                        // current sample is still before the new starttime
                        startSample1 = currentSample;
                    }
                    if (currentTime > lastTime && currentTime <= endTime1) {
                        // current sample is after the new start time and still before the new endtime
                        endSample1 = currentSample;
                    }
                    lastTime = currentTime;
                    currentTime += (double) delta / (double) track.getTrackMetaData().getTimescale();
                    currentSample++;
                }
                movie.addTrack(new AppendTrack(new CroppedTrack(track, startSample1, endSample1)));
            }
            long start1 = System.currentTimeMillis();
            Container out = new DefaultMp4Builder().build(movie);
            long start2 = System.currentTimeMillis();

            String path = _storage.getTempFilePathForVideoId(UUID.randomUUID().toString());
            FileOutputStream fos = new FileOutputStream(path);
            FileChannel fc = fos.getChannel();
            out.writeContainer(fc);

            fc.close();
            fos.close();

So before creating the FileOutputStream and writing to container... can I find out the size before hand ?

**Comment by sannies** [comment]
pseudo code:

long length=0;
for (Box box :out.getBoxes()) {
   length+= box.getSize();
}

this should be a lot more efficient than actual writing.

Best Regards,
Sebastian

2015-04-04 1:34 GMT+02:00 renatofernandes28 <notifications@github.com>:

**Comment by renatofernandes28** [comment]
Thanks that seems to work! Is it possible to get the bitrate of a IsoFile or Movie too ?

**Comment by sannies** [comment]
https://github.com/sannies/mp4parser/blob/e9c8e69dd7156bc1870fdac559af7f9bfe03ff9a/examples/src/main/java/com/googlecode/mp4parser/BitRate.java
