### ISSUE TITLE
Bitrate from an mp4 

### ISSUE THREAD

**Issue by renatofernandes28** [sannies/mp4parser#74]
Is it possible to get the bitrate of an mp4 using the mp4 Parser library ?

**Comment by sannies** [comment]
I added an example:

https://github.com/sannies/mp4parser/commit/e9c8e69dd7156bc1870fdac559af7f9bfe03ff9a
https://github.com/sannies/mp4parser/blob/e9c8e69dd7156bc1870fdac559af7f9bfe03ff9a/examples/src/main/java/com/googlecode/mp4parser/BitRate.java
