### ISSUE TITLE
Track.getDecodingTimeEntries() replacement

### ISSUE THREAD

**Issue by luciancioroga** [sannies/mp4parser#78]
Is there any utility method to replace the old Track.getDecodingTimeEntries()? Thank you!

**Comment by sannies** [comment]
Hi Lucian, 
Track.getDecodingTimeEntries() contained pairs of (count | increment). A pair of 5 | 10 was a shortcut for 10 10 10 10 10 (5 times a 10). The replacement is getSampleDurations which contains the actually value for each sample. When getDecodingTimeEntries returned (5 | 10) the getSampleDurations will returned [10, 10, 10, 10, 10].
This is a lot easier to work with. 
Best Regards,
Sebastian

**Comment by SaMo23** [comment]
hiee this is a code using getDecodingTimeEntries(). can you tell me what can be the code if i use getSampleDurations(). 

for (int i = 0; i < track.getDecodingTimeEntries().size(); i++) {
				TimeToSampleBox.Entry entry = track.getDecodingTimeEntries().get(i);
				for (int j = 0; j < entry.getCount(); j++) {
					// entry.getDelta() is the amount of time the current sample
					// covers.
					if (currentTime <= startTime) {
						// current sample is still before the new starttime
						startSample = currentSample;
					}
					if (currentTime <= endTime) {
						// current sample is after the new start time and still
						// before the new endtime
						endSample = currentSample;
					} else {
						// current sample is after the end of the cropped video
						break;
					}
					currentTime += (double) entry.getDelta() / (double) track.getTrackMetaData().getTimescale();
					currentSample++;
				}
			}

**Comment by PrimankaDEN** [comment]
```
long[] sampleDurations = track.getSampleDurations();
for (int currentSample = 0; currentSample < sampleDurations.length; currentSample++) {
                if (currentTime <= startTime) {
                    // current sample is still before the new starttime
                    startSample = currentSample;
                }
                if (currentTime <= endTime) {
                    // current sample is after the new start time and still before the new endtime
                    endSample = currentSample;
                } else {
                    // current sample is after the end of the cropped video
                    break;
                }
                currentTime += sampleDurations[currentSample];
            }
```
