### ISSUE TITLE
TwoSecondIntersectionFinder - java.lang.NoSuchMethodError: java.util.Arrays.copyOf

### ISSUE THREAD

**Issue by renatofernandes28** [sannies/mp4parser#79]
For android the following method:
Arrays.copyOf() ... is available only on API 9 >
which you use in TwoSecondIntersectionFinder class

If I wanted to support API 8, is there a another version of the MP4Parser I can use beside the latest (or is it possible for you to add System.ArrayCopy() or another method to support lower versions of android

**Comment by sannies** [comment]
Hi,
I wasn't aware that this method is only available in a specific Android API
version.  The method is not doing anything complicated and is merely a
shortcut.
I'll simply create my own backwards compatible shortcut.  Stay tuned.
Am 29.04.2015 05:55 schrieb "renatofernandes28" <notifications@github.com>:

**Comment by renatofernandes28** [comment]
@sannies Thanks for this consideration ... Also in the CroppedTrack class, the getSyncSamples() method uses Arrays.copyOfRange() ... which is also API 9 >

**Comment by sannies** [comment]
fixed https://github.com/sannies/mp4parser/commit/364827d5142472a04229c36a17a7ef9bd1c360dd

**Comment by renatofernandes28** [comment]
CroppedTrack still contains Array.copyRangeOf in getsyncSamples

**Comment by sannies** [comment]
Thanks, the code was no longer used but I left it by mistake. Good catch!

2015-05-13 18:06 GMT+02:00 renatofernandes28 <notifications@github.com>:

**Comment by sannies** [comment]
removed in
https://github.com/sannies/mp4parser/commit/37afd77f3e4152cb2a07fa14287909658e07ffa5

2015-05-18 16:50 GMT+02:00 Sebastian Annies <sebastian.annies@gmail.com>:
