### ISSUE TITLE
Audio syncing problems after appending a third video

### ISSUE THREAD

**Issue by RazorPT** [sannies/mp4parser#86]
I just noticed that if i append more then two videos using the append example the audio starts to lagging behind video on the third video.

I tested this on android while appending 3 mp4 videos recorded with same exact settings, the 3 movies have all between 3 to 10 seconds. I tried this using the latest mp4parser 1.0.6

Any ideas?

**Comment by uditkumawat** [comment]
Hello everyone,I am very grateful to the contributors of MP4Parser.I want to mux one .mp3 file and .mp4 file but the MP3TrackImpl is not working correctly for some songs.So I was trying to convert .mp3 song file to .aac file using java code for android.Please help me .I am in a big trouble.I don't want to use any software tool.

**Comment by sannies** [comment]
Typically audio is a bit shorter than video or the other way around. If audio's duration is shorter then the next audio will start a bit earlier. That is a nasty side-effect. You might correct that by leaving out some frames of audio or video depending on what's longer (CroppedTrack).
