### ISSUE TITLE
Can i use this lib to save media stream data in webrtc?

### ISSUE THREAD

**Issue by hoang89yenthe** [sannies/mp4parser#88]

**Comment by sannies** [comment]
I don't know.  Please describe what you are trying to accomplish.

**Comment by hoang89yenthe** [comment]
I used this example : https://github.com/pchab/AndroidRTC
In this example, they used 2 lib android: libjingle_peerconnection and socket.io_client.
My problem is when media data is streamming, i can not save it as mp4.
Please check my question in here : https://github.com/pchab/AndroidRTC

**Comment by sannies** [comment]
Ok.  Mp4  is a container format .  Mp4parser can package supported formats/codecs in MP4 containers . What kind of codec is used for webrtc?

**Comment by hoang89yenthe** [comment]
VP8 for video and Opus for Audio

**Comment by sannies** [comment]
Ok, now we are getting closer! 
Afaik there is no specification that allows you package VP8 and/or Opus in MP4 containers. Therefore the mp4parser library won't be able to help you.

**Comment by mlaggner** [comment]
according to http://opus-codec.org/docs/ - http://opus-codec.org/docs/opus_in_isobmff.html it should be possible to package opus in mp4
