### ISSUE TITLE
Conversion of mp3 file to aac file for using in AACTrackImpl 

### ISSUE THREAD

**Issue by uditkumawat** [sannies/mp4parser#89]
Hello everyone,I am very grateful to the contributors of MP4Parser.I want to mux one .mp3 file and .mp4 file but the MP3TrackImpl is not working correctly for some songs.So I was trying to convert .mp3 song file to .aac file using java code for android.Please help me .I am in a big trouble.I don't want to use any software tool.

**Comment by sannies** [comment]
Are you recording the file on the phone as mp3? Then please don't do it.
Record it on the phone as AAC. Is the MP3 delivered with the application.
Then please don't do it. Convert the file to AAC on your PC and package the
AAC file.
MP3 has an unbelievably low priority as it is totally outdated and next to
no one uses MP3 in MP4 containers. I am available as a freelancer if this
is a business requirement in any way for you or your company.

Grüße,
Sebastian

2015-06-15 16:44 GMT+02:00 udit <notifications@github.com>:

**Comment by uditkumawat** [comment]
I have all my files in .mp3 format .So I was trying to convert the file to .aac when it is used for muxing.I will use AACTrackImpl.It should be real time conversion.

**Comment by sannies** [comment]
Hi Udit,

then please do convert the files. Trying doesn't help. You need to use
something like ffmpeg to convert them. The result of the conversion can
then be read by the AACTrackImpl.

Best Regards,
Sebastian

2015-06-15 16:51 GMT+02:00 udit <notifications@github.com>:
