### ISSUE TITLE
Slow down video segments using MP4Parser

### ISSUE THREAD

**Issue by nitesh201** [sannies/mp4parser#91]
Hi, I'm trying to naively slowdown (i.e. halve the framerate) particular segments in a video. Is this something that can be done with MP4Parser?

**Comment by sannies** [comment]
The picture timing is determined by either the "Decoding Time to Sample
Box" located at /moov/trak/mdia/minf/stbl/stts or in case of a fragmented
MP4 file in the Track Run Box located at /moof/traf/trun. If you change the
numbers in these boxes the video is going to play slower or faster.
Be careful:
* If you insert or remove bytes in regular MP4s (stts case) the offsets in
other boxes are no longer correct
* The audio is not slowed down.
* The total length might need to be corrected

Best Regards,
Sebastian



2015-06-27 0:18 GMT+02:00 Nitesh Menon <notifications@github.com>:

**Comment by flieks** [comment]
Hi
if you record a movie on android, is that a fragmented mp4 or not ?
where is this moof/traf/trun folder; i can't find it
