### ISSUE TITLE
How to merge audio and video file in android

### ISSUE THREAD

**Issue by feelzdroid** [sannies/mp4parser#93]
Hi,
Thanks for the great mp4parser lib, i have few queries related to audio video muxing.

We used the below code in android and tried, but we are getting indexoutofbound exception in H264TrackImpl,  We have kept a working mp4 file in the specific directory and trying but no luck.

Here is the code,

            File sdCard = Environment.getDataDirectory();

            String videofilepath = Environment.getExternalStorageDirectory().toString()+"/video.mp4";
            String audiofilepath = Environment.getExternalStorageDirectory().toString()+"/audio.aac";
            File file=new File(videofilepath);

            H264TrackImpl h264Track = new H264TrackImpl(new FileDataSourceImpl(videofilepath));
            AACTrackImpl aacTrack = new AACTrackImpl(new FileDataSourceImpl(audiofilepath));

            Movie movie = new Movie();
            movie.addTrack(h264Track);
            movie.addTrack(aacTrack);

            Container mp4file = new DefaultMp4Builder().build(movie);

            FileChannel fc = new FileOutputStream(new File(Environment.getExternalStorageDirectory().toString() + "/video.mp4")).getChannel();
            mp4file.writeContainer(fc);
            fc.close();

**Comment by sannies** [comment]
sorry for not responding any earlier. But in case you are still interested and haven't figured it out: 
H264TrackImpl is used to import Annex B 'raw' h264 files. 
MP4 files have to be open with the MovieCreator class. The resulting Movie object has a number of tracks which can then be handled like you do it with the h264Track.
