### ISSUE TITLE
JPGs to video

### ISSUE THREAD

**Issue by baole** [sannies/mp4parser#94]
Is there any sample code to convert multiple JPG files into a video file?

**Comment by sannies** [comment]
Hi,
there are multiple ways of doing so:
1. Re-encode as a proper video with tools like ffmpeg, x264, x265 or
2. create an MJPEG movie which might be based on the OneJpegPerIframe class
(the class needs some minor work to support MJPEG tracks which are not tied
to another 'normal' video track)

What do you want to do ?

Best Regards,
Sebastian

2015-07-08 13:36 GMT+02:00 baole <notifications@github.com>:

**Comment by baole** [comment]
Thanks Sebastian for promptly response. Actually, I want to convert multiple images to a video on Android. This [SO](http://stackoverflow.com/questions/22996378/android-encoder-muxer-raw-h264-to-mp4-container/23000620#23000620)  gives me a hint to create a video from h264 files. I stuck at how to convert jpg/png image into h264 file.

**Comment by baole** [comment]
Hi Sebastian,

I changed OneJpegPerIframe which changed ImageIO by Android specific classes and try to create a video from .jpeg files. However, OneJpegPerIframe requires alignTo's track object in its constructor and then align to existent track. Is there anyway to make a jpeg file to a (independent) track?

**Comment by sannies** [comment]
I'll close the issue as there was no more activity.

**Comment by khan-tm** [comment]
Why're you not providing a clean example! 
I found almost same thing here https://github.com/sannies/mp4parser/issues/182.
