### ISSUE TITLE
Issue using in Android studio 

### ISSUE THREAD

**Issue by amit-bst** [sannies/mp4parser#95]
Hi i tried to add to android studio

```java

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile 'com.googlecode.mp4parser:isoparser:1.0.5.4'
}
```

But it gives me 

Error:(24, 13) Failed to resolve: com.googlecode.mp4parser:isoparser:1.0.5.4
Show in File
Show in Project Structure dialog

**Comment by sannies** [comment]
This is not a  isoparser specific question. It's just about resolving an
external library. I guess it's rather a question for the Android Studio
mailing list.

amit-bst <notifications@github.com> schrieb am Sa., 11. Juli 2015 19:44:

**Comment by amit-bst** [comment]
okay what i did was use the jar simply and it worked. There might be some issue in gradle system.
