### ISSUE TITLE
hello, my application crash as Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.coremedia.iso.boxes.FileTypeBox

### ISSUE THREAD

**Issue by xu6148152** [sannies/mp4parser#96]
this is my code:

String audio = audioFile.getAbsolutePath();
        String video = videoFile.getAbsolutePath();

        try {
            Movie countVideo = MovieCreator.build(video);
            Movie countAudio = MovieCreator.build(audio);

            Track audioTrack = countAudio.getTracks().get(0);
            countVideo.addTrack(audioTrack);

            {
                Container out = new DefaultMp4Builder().build(countVideo);
                FileOutputStream fos = new FileOutputStream(new File(
                        FileUtil.getCacheDirectory(VideoRecordActivity.this, true),
                        "output.mp4"));
                out.writeContainer(fos.getChannel());
                fos.close();
            }

        } catch (IOException e) {
            e.printStackTrace();
        }

I want to merge 2 mp4 files, one is video, the other is audio, but it will crash like above code.

Can any help me ? Thank you very much.

**Comment by sannies** [comment]
java.lang.ClassNotFoundException: com.coremedia.iso.boxes.FileTypeBox

means that the class "com.coremedia.iso.boxes.FileTypeBox" has not been
found. Is it on your classpath? Did you use anything like proguard that
might have removed the class from the final APK?

2015-07-13 9:12 GMT+02:00 xu6148152 <notifications@github.com>:

**Comment by xu6148152** [comment]
Thank you for @sannies  replying, I have resolved the problem, because i miss aspectjrt.jar

**Comment by loikfb** [comment]
I have the same issue, I've try to add aspectjrt-1.8.7.jar, but when I compile for a release apk with proguard activated, I have a compiled Error like "Can't write ... Can't read .."

**Comment by sannies** [comment]
If you had the same issue you could apply the same solution. Obviously you
don't have the same issue.
Please open a new issue and describe your case in detail. Otherwise I will
not be able to help.

2015-11-25 20:35 GMT+01:00 loikfb <notifications@github.com>:
