### ISSUE TITLE
How to enable playback while downloading a mp4 file (HTTP FastStart) with mp4parser?

### ISSUE THREAD

**Issue by youzai001** [sannies/mp4parser#97]
MP4Box (https://gpac.wp.mines-telecom.fr/mp4box/) can do it. does mp4parser can do the same thing?

with MP4Box, to prepare a file for simple progressive HTTP download, the following instruction will interleave file data by chunks of 500 milliseconds in order to enable playback while downloading the file (HTTP FastStart) 

MP4Box -inter 500 file.mp4

**Comment by sannies** [comment]
By default the chunks are interleaved everleaved every two seconds when
being muxed with the DefaultMp4Builder. The 'table of contents' (the moov
box which also contains the codec initialization and so on) is written in
the beginning of the file anyways. So it's very similar to what MP4Box is
doing and HTTP fast start (which is more of a player feature) should work.

2015-07-22 12:24 GMT+02:00 youzai001 <notifications@github.com>:

**Comment by youzai001** [comment]
I have tested it, it works for me. Thank you.
