### ISSUE TITLE
Resolutions and Frame-rates

### ISSUE THREAD

**Issue by aliudurim** [sannies/mp4parser#99]
Is it possible to change resolutions and frame-rates with mp4parser.

**Comment by sannies** [comment]
Hi, 
no. This is not possible (I got the feeling I already answered this question but can't see when and where). The resolution is determined during encoding. The mp4parser does not encode - it's dealing with videos on container level only. 
You might increase the framerate as the frames' duration is in the container but you cannot remove any frames as h264 frames depend on each.
Grüße,
Sebastian
